### ISSUE TITLE
Interact with core contracts

### ISSUE THREAD

**Issue by Anas2001** [iotaledger/wasp-legacy#1078]
How it's possible to interact with core contracts https://wiki.iota.org/smart-contracts/guide/core_concepts/core_contracts/overview of wasp node for example gov-contract https://wiki.iota.org/smart-contracts/guide/core_concepts/core_contracts/governance? There are no exapmle about that

**Comment by howjmay** [comment]
Actually we do have. See here https://github.com/iotaledger/wasp/tree/wasmdust/contracts/wasm/corecontracts

**Comment by Anas2001** [comment]
Ok thanks @HowJMay but how can I call the functions of a contract? Are there a way to call it from **wasp-cli** ?

**Comment by howjmay** [comment]
I haven't tried to call it with wasp-cli. May I know the scenario of your usage more detailed?

**Comment by Anas2001** [comment]
I want to set the fees for calling or deploying EVM smart contract

**Comment by jorgemmsilva** [comment]
@Anas2001 that won't be possible. In the incoming release we actually re-designed the fee model and everything is gas-based, there won't be a way to set "contract-specific fees". If you have a contract that wants to charge for usage, the contract itself should do it.

**Comment by Anas2001** [comment]
@jorgemmsilva waht about deploying contracts with fees ? and can we whiteliste EVM addresses for deplyoing contracts?

**Comment by Anas2001** [comment]
@jorgemmsilva sorry but not nice to close the issue without solving the issue
