### ISSUE TITLE
dwf not incrementing amount correctly

### ISSUE THREAD

**Issue by avlo** [iotaledger/wasp-legacy#110]
is anyone successfully running `wasp-cli` `donatewithfeedback` SC with runtime `amount` and/or `feedback` key/values? 
 and confirmed those values are indeed used by SC?

below are my steps in attempting the same.  it assumes `goshimmer` (with `waspconn`) is already installed on your system.

SC seems to run, but i'm specifically not seeing donation `amount/feedback` used or shown anywhere in the dwf dashboard.  what's further concerning is no logs from any of the attempted SC source files appear in stdout, which further tells me none of the SC's attempted are actually executed.

hoping someone can follow the steps and point out if/where i'm missing something:

// install wasp executables
`$ cd <wasp_root_dir>`
`$ go install ./...`  // should install wasp, wasp-cli, wasp-cluster

// start cluster
`$ wasp-cluster init my-cluster` // should create "my-cluster" directory with necessary files in it
`$ cd my-cluster/`
`$ wasp-cluster start`

// initialize wallet, set utxo, confirm address and balance
`$ mkdir <some_dir> && cd <some_dir>`
`$ wasp-cli init`
`$ wasp-cli set utxodb true`
`$ cat wasp-cli.json` // should show utxo true

// add funds to balance
`$ wasp-cli balance` // should show nothing
`$ wasp-cli address`
`$ wasp-cli request-funds`
`$ wasp-cli balance` // should so a non-zero balance

// deploy chain
`$ wasp-cli chain deploy --chain=<chain_name> --description="chain description"`
// open localhost:7000 in webbrowser, above created chain should be visible

// deploy contract (3 variations below, each attempted unsuccessfully)
`$ wasp-cli chain deploy-contract examplevm <chain_name> "chain description" <wasp_root_dir>/contracts/rust/donatewithfeedback/wasmmain/donatewithfeedback.go`
  or
`$ wasp-cli chain deploy-contract examplevm <chain_name> "chain description" <wasp_root_dir>/contracts/rust/donatewithfeedback/src/donatewithfeedback.rs`
  or 
`$ wasp-cli chain deploy-contract examplevm <chain_name> "chain description" <wasp_root_dir>/contracts/rust/donatewithfeedback/donatewithfeedback.go`
*(note: `examplevm` in each above was also attempted replaced with `wasmtimevm`, but still no success)*

// call donate with amount "2" 
`$ wasp-cli chain post-request <chain_name> donate string amount string 2`
***// open localhost:7000 in webbrowser, balance has NOT increased by 2 as expected- only 1***

**Comment by lunfardo314** [comment]
irrelevant due to recent refactoring
