### ISSUE TITLE
Wasp crashes after restarting (segfault)

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#1121]
# Problem description

Running Wasp (`develop 0.3.0`) for the first time works fine, creating a chain, etc. But once I deploy a chain and close Wasp, then re-run it again it immediately panics:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11173a1]
```

I can only run wasp again if I remove the database folder contents and start over but it's deterministically reproducable. 

# Proposed solution

Ideally wasp works more then 1 run and does not crash on the second time :stuck_out_tongue:

**Comment by jorgemmsilva** [comment]
closing as this was fixed on https://github.com/iotaledger/wasp/pull/1128
