### ISSUE TITLE
EVM getEntropy magic contract function can't be a view

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#1133]
The current `getEntropy` function in the ISC magic contract is marked as a view, however, due to the entropy being generated with the consensus it is not available in the pre-consensus state and can therefore not be a view function. It might be interesting to also emit an Event with this function so that there's always a reference to the generated entropy within the EVM in case this function is used. There might be similar functions marked as `view` like this but this was the one I came across during the testing.

**Comment by dessaya** [comment]
solved in #1413
