### ISSUE TITLE
.wasp-cli request-funds gives error

### ISSUE THREAD

**Issue by jigsnptel** [iotaledger/wasp-legacy#1155]
i am setting up a wasp chain and getting following error while requesting funds:

./wasp-cli request-funds
error: BalanceIOTA: GetConfirmedOutputs: GetUnspentOutputs: Get "http://shimmer.chrysalis2.com:8080/ledgerstate/addresses/1FgMRuPMp8iMwVdifoZxeu8GNzF9kDqcPp7jfMYtwWZ5d/unspentOutputs": dial tcp 49.12.73.71:8080: connect: connection refused

my wasp-cli.json contents are:
{ "wallet":{ "seed": "j0x483f2BF505E7e494a87cC4AC9eD563e21756ec49" }, "wasp":{ "0": "api": "127.0.0.1:9090", "namomsg":127.0.0.1:5550", "peering":127.0.0.1:4000" } }, "goshimmer":{ "api":"shimmer.chrysalis2.com:8080", "faucetpowtarget": -1 } }

kindly help with the issue

**Comment by jorgemmsilva** [comment]
seems that  http://shimmer.chrysalis2.com is no longer active.

I would advice to use the new Shimmer public beta network from now on.  The newer wasp version (from `develop` branch)  is compatible with it. There is not a lot of documentation at the moment, but feel free to post issues here on github or reach out via discord and we will try to help you.
