### ISSUE TITLE
not able to see my contract on chain

### ISSUE THREAD

**Issue by jigsnptel** [iotaledger/wasp-legacy#1177]
hi,
i have deployed the contract on wasp-cli evm chain using Remix and metamask, even i am able to send the transaction to the deployed contract.  How do you check whether the ontract is deployed it or not. i tried ./wasp-cli chain list-contracts, but it is not showing my contracts. even ./wasp-cli chain metrics is not showing anything. pls help

**Comment by jorgemmsilva** [comment]
` ./wasp-cli chain list-contracts` will only show WASM-based contracts that have been deployed to the chain.

To query EVM-based contracts you can use the contract address and call `getCode`:
https://ethereum.stackexchange.com/a/28527
