### ISSUE TITLE
Getting Bad Gateway error

### ISSUE THREAD

**Issue by mahesh2392** [iotaledger/wasp-legacy#1190]
We are try to communicate with wasp node from different system with call view request but getting error "502 Bad Gateway", we configure ip accordingly still got same error what will be the possible cause?

**Comment by jorgemmsilva** [comment]
That seems something specific to your infrastructure setup.
Does the same view request work when executed from the same machine the node is running on?

**Comment by mahesh2392** [comment]
Does the same view request work when executed from the same machine the node is running on? ----> yes we are able to get response. 
Can we do call view /post request to wasp node from wallet(wasp-cli) which is on different machine (with current available wasp node and wasp-cli)?

**Comment by jorgemmsilva** [comment]
For sure. The "bad gateway" error makes me think some kind of proxy/load balancer is preventing the view call request to reach wasp
