### ISSUE TITLE
`make` generates a binary call `cmd`

### ISSUE THREAD

**Issue by dessaya** [iotaledger/wasp-legacy#1194]
`make` currently generates the following binaries:

```
cmd*
dbinspector*
schema*
snapshot*
submsg*
wasp*
wasp-cli*
wasp-cluster*
```

Note that all are properly named except `cmd`, which corresponds to the `gascalibration`.

We should do one of the following:

* Fix the `gascalibration` tool to generate a binary called `gascalibration`
* Maybe we don't need to compile everything when running `make`? Just `wasp` and `wasp-cli`?

**Comment by jorgemmsilva** [comment]
>Maybe we don't need to compile everything when running make? Just wasp and wasp-cli?

absolutely agree. I would add `wasp-cluster` as well, for convenience
