### ISSUE TITLE
Metamask shows no gas fees when making a transaction

### ISSUE THREAD

**Issue by lmoe** [iotaledger/wasp-legacy#1221]
When you interact with a Web3 website and want to approve a transaction, Metamask will show 0 gas fees and costs.
This happens because we define the gas budget inside the metadata which Metamask does not read.

A start would be to implement https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_estimategas

**Comment by jorgemmsilva** [comment]
https://github.com/iotaledger/wasp/blob/add_l2_withdraw/packages/evm/jsonrpc/service.go#L184-L186
estimate gas is implemented afaik :point_up: , but probably needs to be improved

edit: I think the gas limit is being correctly calculated, but not the price of the fees
