### ISSUE TITLE
Withdraw failed

### ISSUE THREAD

**Issue by huggre** [iotaledger/wasp-legacy#1373]
Hi, I'm working on the variant of this solidity contract: https://gist.github.com/gorgos/2b161ddb508989f4f0d733602054831f
Everything woks fine except when I try to execute the withdrawMoney() function on the Shimmer EVM testchain.
Status = "false Transaction mined but execution failed"
Function works perfectly with the Remix VM chains.
Any ideas?

**Comment by jorgemmsilva** [comment]
@huggre I messaged you on discord. Please retry this, does it still happen? We have released a new wasp version to the testnet that might have fixed the issue you're having.

**Comment by muXxer** [comment]
Can this be closed @huggre ?
