### ISSUE TITLE
Goshimmer node crashes creating new chain on refactor branch

### ISSUE THREAD

**Issue by sascha1337** [iotaledger/wasp-legacy#140]
> Error from wasp-cli
![image](https://user-images.githubusercontent.com/12372821/113837856-d2bc4180-97c0-11eb-85ea-19449a4bbfcb.png)

>goshimmer node
![image](https://user-images.githubusercontent.com/12372821/113837923-e071c700-97c0-11eb-8638-3cd1e3a4cf21.png)

Any hint? Thanks !

**Comment by dessaya** [comment]
The refactor is not finished yet, so it is expected to fail atm. We are working on it.
