### ISSUE TITLE
Wrong link for snapshot

### ISSUE THREAD

**Issue by elRaulito** [iotaledger/wasp-legacy#147]
At https://github.com/iotaledger/wasp/blob/master/docs/docs/runwasp.md
**on step 2** 
`curl 'https://github.com/iotaledger/goshimmer/raw/master%2Bwasp/snapshot.bin' -O`
gives an error because it's a redirect link
the correct command should be
`curl 'https://raw.githubusercontent.com/iotaledger/goshimmer/master%2Bwasp/snapshot.bin' -O `

**Comment by dessaya** [comment]
Fixed in 3b7969b6c4ad8d27552310c9353ba0f033ee940d
