### ISSUE TITLE
`go get github.com/iotaledger/wasp/packages/solo` does not work

### ISSUE THREAD

**Issue by crazyfree** [iotaledger/wasp-legacy#1485]
Hi, 

when trying to create my first ISC follows [this article](https://wiki.iota.org/shimmer/smart-contracts/guide/solo/first-example) with solo@v0.3.8, i faced the error as title 
`unknown field 'ISCContract' in struct literal of type vm.Config`. 
Digging deeper i found that vm.Config does not contain `ISCContract` key but got reference in 
`github.com/iotaledger/wasp@v0.3.8/packages/vm/core/evm/emulator/emulator.go:124:26:` 
as shown in attached image.

<img width="925" alt="Screen Shot 2022-12-03 at 10 28 04" src="https://user-images.githubusercontent.com/3860469/205420573-2140ea10-303f-4393-91f6-1e07265d1bf3.png">

Did I do something wrong? Any idea to get it up and run properly?

**Comment by dessaya** [comment]
I think there is something wrong with your package versions. This is what I get when I check out the `v0.3.8` tag and run the `TestTutorialFirst`:

```
~/wasp/v0.3.8 (v0.3.8) $ go test ./documentation/tutorial-examples/test -v -run TestTutorialFirst
=== RUN   TestTutorialFirst
[...]
--- PASS: TestTutorialFirst (0.03s)
PASS
ok  	github.com/iotaledger/wasp/documentation/tutorial-examples/test	0.070s
```

Check your `go-ethereum` dependency. The `go.mod` file states that it should be at commit `46bc5f1c51d5` (branch `isc`). The definition of `vm.Config` is different than your scrreenshot:

https://github.com/iotaledger/go-ethereum/blob/isc/core/vm/interpreter.go#L39

**Comment by crazyfree** [comment]
@dessaya I've used `go get github.com/iotaledger/wasp/packages/solo@v0.3.8`

<img width="825" alt="Screen Shot 2022-12-05 at 09 46 43" src="https://user-images.githubusercontent.com/3860469/205538445-591336bc-326b-4247-ab5e-98ada1d93f6f.png">

**Comment by dessaya** [comment]
Ok, we have a couple of `replace` directives in our go.mod:

```
replace (
	github.com/anthdm/hbbft => github.com/kape1395/hbbft v0.0.0-20220823095040-07b2628097ef
	github.com/ethereum/go-ethereum => github.com/iotaledger/go-ethereum v1.10.10-0.20220921180119-46bc5f1c51d5
	go.dedis.ch/kyber/v3 v3.0.14 => github.com/kape1395/kyber/v3 v3.0.14-0.20210622094514-fefb81148dc3
)
```

It seems that `go get` does not automatically apply the same replacements. Adding that to your `go.mod` should fix the issue.

For a future release we will try to fix our forks so that this manual step is not required.

**Comment by crazyfree** [comment]
yeah thanks, it works perfectly
