### ISSUE TITLE
Idea: implement ErgoScript support for IOTA ISCP

### ISSUE THREAD

**Issue by kranebitt** [iotaledger/wasp-legacy#166]
ErgoScript is widely known for being lean and light-weight and useful. It is currently implemented on the ERGO blockchain but should basically run on other UXTO protocols as well
and enables many different use cases within the Ergo and Cardano Ecosystem.

[ErgoScript Paper](https://ergoplatform.org/docs/ErgoScript.pdf)

**Comment by lunfardo314** [comment]
that would be more fitting to the L1 ledger than to ISCP which is on top

**Comment by kranebitt** [comment]
After reading the documentation I agree. It could run on L2 through a virtual machine, but L1 would be preferable. Therefore I proposed #1307 in the GoShimmer repository.
