### ISSUE TITLE
Conflicting L1 transaction when setting up a new chain

### ISSUE THREAD

**Issue by adrian-grassl** [iotaledger/wasp-legacy#1680]
- The first transaction consumes one basic output 1 and creates a new alias output 2 (chain alias) and a new basic output 3 for the remaining funds.
- The second transaction ("init tx") tries to consume basic output 1, which has already consumed before.
- I assume either the second tx is issued before the first one got confirmed.
- Depending on the spammer settings (L1 private tangle) sometimes tx 1 has already been confirmed an it looks fine, but sometimes there's the issue described above

**Comment by muXxer** [comment]
Yeah I'm still working on L1 connection changes.
I guess it's caused by that.
