### ISSUE TITLE
There is no way of retrieving the SN after calling foundryCreateNew

### ISSUE THREAD

**Issue by dessaya** [iotaledger/wasp-legacy#1900]
If I call the `foundryCreateNew` endpoint of the `accounts` core contract, there is no way to find out the foundrySN of the newly created foundry.

A possible solution is triggering an event.

Another is changing the ISC receipt to include the result of the call.

**Comment by ivange94** [comment]
Fixed in https://github.com/iotaledger/wasp/pull/2083
