### ISSUE TITLE
Every Wasp-cli command fails with "first path segment in URL cannot contain colon"

### ISSUE THREAD

**Issue by kthecoder** [iotaledger/wasp-legacy#1932]
_Using [v0.5.0-alpha.7](https://github.com/iotaledger/wasp/releases/tag/v0.5.0-alpha.7)_

No matter what command I try to execute on the wasp-cli I always get this error:

```cmd
wasp-cli login
Username: wasp
Password: error: parse "127.0.0.1:9090/auth": first path segment in URL cannot contain colon
goroutine 1 [running]:
runtime/debug.Stack()
```

```cmd
first path segment in URL cannot contain colon

goroutine 1 [running]:

runtime/debug.Stack()
```

Here are the steps I have done so far:

1. Install Node.js
1. Install Hardhat
1. Docker Desktop (Or some version of docker that can spin up containers)
   1. Grab the docker image : `git clone https://github.com/iotaledger/wasp.git`
   1. Initiate :
      1. `cd wasp/tools/local-setup`
      1. `docker-compose up`
1. Install the Wasp-CLI
   1. Get the Binary from : `https://github.com/iotaledger/wasp/releases`
   1. Add the binary to PATH
   1. The following steps are done by modifying a "wasp-cli.json" file in the current directory of the terminal
   1. Initialize the wasp-cli with : `wasp-cli init`
   1. Add the address for the L1 Layer : `wasp-cli set l1.apiaddress http://localhost:14265`
   1. Only for test networks, add the faucet address : `wasp-cli set l1.faucetaddress http://localhost:8091`
   1. Add a wasp node : `wasp-cli wasp add wasp-0 127.0.0.1:9090`

**Comment by fijter** [comment]
Please make sure you enter the wasp node with the right prefix, either https or HTTP:

`wasp-cli wasp add wasp-0 127.0.0.1:9090` should be `wasp-cli wasp add wasp-0 http://127.0.0.1:9090`.

You can use the `set` command to overwrite or manually edit `wasp-cli.json` to update it.

Please let me know if this resolves it so we can close the ticket :)

**Comment by kthecoder** [comment]
That indeed fixed the error. But the response is now 404 not found.

Wasp Docker says : ```ERROR   WebAPI  Compatibility Error Handler: code=404, message=Not Found```

```cmd
wasp-cli chain deploy --peers=foo,bar,baz --chain=mychain --description="MyChain"
error: 404 Not Found

Not Found
goroutine 1 [running]:
runtime/debug.Stack()
```

**Comment by fijter** [comment]
Can you run it with `--verbose` at the end and post the full output of that?

Can you also paste the output of `wasp-cli peering list-trusted` maybe (feel free to leave out any sensitive data like IP addresses the might result in).

**Comment by kthecoder** [comment]
Verobse Output: 
```md
using L1 API http://localhost:14265
using L1 API http://localhost:14265
using Wasp host http://127.0.0.1:9090
error: 404 Not Found

Not Found
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/iotaledger/wasp/tools/wasp-cli/log.Fatalf({0x30325ad?, 0x18?}, {0xc001f1f8b0?, 0xc00011a099?, 0x0?})
	/__w/wasp/wasp/tools/wasp-cli/log/log.go:76 +0x3c
github.com/iotaledger/wasp/tools/wasp-cli/log.Check({0x3563920, 0xc0024d3600})
	/__w/wasp/wasp/tools/wasp-cli/log/log.go:151 +0x1d7
github.com/iotaledger/wasp/tools/wasp-cli/chain.doDKG({0xc0011ac476, 0x6}, {0xc000fa8390, 0x3, 0x39?}, 0xc0001c0500?)
	/__w/wasp/wasp/tools/wasp-cli/chain/rundkg.go:67 +0x188
github.com/iotaledger/wasp/tools/wasp-cli/chain.initDeployCmd.func1(0xc001620000?, {0xc000fa6200?, 0x4?, 0x4?})
	/__w/wasp/wasp/tools/wasp-cli/chain/deploy.go:86 +0x1d8
github.com/spf13/cobra.(*Command).execute(0xc001620000, {0xc000fa61c0, 0x4, 0x4})
	/github/home/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00017a900)
	/github/home/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/github/home/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/__w/wasp/wasp/tools/wasp-cli/main.go:72 +0x25
```

Trusted Peering List :
```md
error: 404 Not Found

Not Found
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/iotaledger/wasp/tools/wasp-cli/log.Fatalf({0x30325ad?, 0x18?}, {0xc000773c80?, 0xc00048c291?, 0x0?})
	/__w/wasp/wasp/tools/wasp-cli/log/log.go:76 +0x3c
github.com/iotaledger/wasp/tools/wasp-cli/log.Check({0x3563920, 0xc000778100})
	/__w/wasp/wasp/tools/wasp-cli/log/log.go:151 +0x1d7
github.com/iotaledger/wasp/tools/wasp-cli/peering.initListTrustedCmd.func1(0xc000452300?, {0x44381e0?, 0x0?, 0x0?})
	/__w/wasp/wasp/tools/wasp-cli/peering/listtrusted.go:29 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc000452300, {0x44381e0, 0x0, 0x0})
	/github/home/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025e300)
	/github/home/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/github/home/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/__w/wasp/wasp/tools/wasp-cli/main.go:72 +0x25
```
