### ISSUE TITLE
Optimize the block sync for longer chains.

### ISSUE THREAD

**Issue by kape1395** [iotaledger/wasp-legacy#1937]
The node can have OOM if it is added as an access node for a chain with a lot of blocks. It will ask other nodes for blocks and will collect all the blocks in memory because it can fetch blocks from the latest one and can commit them from the oldest only. Several ideas for optimization:

  - Store the received but not yet committed blocks in the WAL instead of memory. That will solve the OOM problem.
  - If the last block the node knows has StateIndex=X, and now it wants the AliasOutput=AO with stateIndex=Y, and Y>X, then it can ask -- give me Y-X blocks, ending at AO. This will decrease messaging overhead. Nevertheless, the receiving node will be able to validate the received blocks by their hashes / commitments and to store them in the WAL.
  - First, ask for a chain of hashes (block headers), and then fetch blocks in the order they can be committed. This approach has a  drawback -- the receiving node cannot validate the blocks until it receives all the chain, until the latest committed AO. An adversary can feed trash instead of blocks. And we will have to store all the chain variants, because only the latest will indicate, which chain was the correct one.

**Comment by kape1395** [comment]
Also, the nodes sending blocks should rate-limit these operations.

**Comment by Juliusan** [comment]
Just to note that all the received blocks are already stored in WAL. To implement the first suggestion it would be enough to simply remove the received block from the memory and reload it from WAL on commit. If the WAL gets messed up in between (should happen extremely rarely) the block can be redownloaded on commit.
