### ISSUE TITLE
Can we have log nanos with leading/trailing zeros?

### ISSUE THREAD

**Issue by kape1395** [iotaledger/wasp-legacy#1955]
```
2023-02-18T13:19:31.298115399Z  INFO    Peering ------------- PeeringURL = 0.0.0.0:4000... 
2023-02-18T13:19:34.82420357Z   INFO    Peering ------------- PeeringURL = 0.0.0.0:4000...
```
Having the nanos of the same number of digits would make it easier to sort the records.

**Comment by muXxer** [comment]
Tbh I don't think that would be easy at all. :(
That's super deep in the Uber lib we are using.
We would need to fork that and use the fork in hive.go

**Comment by kape1395** [comment]
Then maybe that's not worth it. Sorry for the noise.

**Comment by muXxer** [comment]
Naahh no worries 😂
