### ISSUE TITLE
Why do we prohibit to add self as a trusted peer?

### ISSUE THREAD

**Issue by kape1395** [iotaledger/wasp-legacy#1958]
```
	selfPubKey := c.peeringService.GetIdentity().PublicKey
	if publicKey.Equals(selfPubKey) {
		return apierrors.SelfAsPeerError()
	}

```
I think we should either allow or just ignore such requests.
Such a request could be useful to override name of the self peer.

**Comment by lmoe** [comment]
Hope I understand it correctly..

I found it confusing why it was possible to trust your own node. Shouldn't the node always trust itself?
But I think that one should be able to rename his own node.

We do have a route `node/identity` which returns the peering info. What about adding a PUT method with which you can change your name instead? I think that would make the use case a bit clearer.

**Comment by jorgemmsilva** [comment]
this was causing issues, for example during DKG if you would specify your "peer name" it would crash.
also as a concept "trusting your own node" seems a bit silly :smile:
