### ISSUE TITLE
Gas in EVM doesn't reflect actual gas used

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2015]
When doing a transaction through Metamask you get the gas price field, it's auto filled (this logic is a bit weird given it always takes the highest value you've ever set, this is likely due to how metamask works though). If you change it though that is ignored, it shows up in the EVM explorer as that specific gas price (so if I set it to 0 it shows up in the explorer as 0) but it actually deducted a high amount of gas instead - This becomes way more apparent when changing the gasPerToken ratio in the governance contract. 

Expected behavior: The gas estimation including gas price reflects the settings well so the estimated gas price comes close to the actual gas price and the EVM transaction should take the real gas price into account which is enforced, not the given gas price. Likely this behavior can't really be changed due to how a transaction is built so I guess we need to change the logic to just decline a transaction if the gas price is below the set value.

**Comment by dessaya** [comment]
The issue is caused by the chain owner not being able to set the gas fee, because the current gas fee is too high and the request fails with "gas budget exceeded". We should skip charging the gas fee at least for this request.
