### ISSUE TITLE
Stardardize the binary format of all events triggered by core contracts

### ISSUE THREAD

**Issue by dessaya** [iotaledger/wasp-legacy#2086]

**Comment by dessaya** [comment]
Right now events triggered by core contracts are mostly strings. E.g.:

```
ctx.Event(fmt.Sprintf("[deploy] name: %s hname: %s, progHash: %s, dscr: '%s'", ...))
```

Events should have a standard serialized form that allows the client to decode the information programatically. For example:


```
ctx.Event(&root.DeployContractEvent{
  Name: ...,
  Hname: ...,
  ProgHash: ...,
}.Bytes())
```

**Comment by lmoe** [comment]
I wanted to change this for so long, one thing that was putting it off for me was the integration with WASM contracts. I assume we would like to want those structured events there as well? That would require quite a bit of refactoring on the existing contracts, wasmlibs and vm.

**Comment by howjmay** [comment]
@dessaya @lmoe 
In wasmlib, we encode an event object in the following way.

```
<contract_name>.<event_name>|<1st_field_in_event_obj>|<2nd_field_in_event_obj>
```

Here `.` and `|` are the separators that we use.

So is it OK to standardize in this way?

**Comment by dessaya** [comment]
But is it a binary or text format?

IMO we should use a binary format. e.g. instead of storing the contract name (variable length), we store the hname (4 bytes). No separator needed.

**Comment by howjmay** [comment]
It is in text format. 

How about formatting to binary format. 

The first 4 bytes is hname of the contract. The following bytes are the compacted bytes of event objects. But in this way, there is no identifier to show which event this object belongs to. And the other problem is the string fields. May be we should set a limit of string length and put the string length as prefix of the string in binary format. I think basically I can call the functions in `packages/util/rwutil.go`

@BugFreeSoftware @dessaya @lmoe how do you think?

**Comment by howjmay** [comment]
An PR is opened. Please take a look. If everything is fine, then I will work on this way
