### ISSUE TITLE
gas estimation with EVM `gasleft()` or a static call on magic contracts fails

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2105]
Reproducible code: 

```
pragma solidity ^0.8.3;

import "@iscmagic/ISC.sol";

contract Gasleft {

    function test() public returns (uint256 gasLeft) {
        bytes32 e = ISC.sandbox.getEntropy();
        gasLeft = gasleft();
    }
}
```

because functions like gasLeft (or callStatic in ethers.js) do a view call on a call function to see how much gas that function would use and the magic contracts do not expect a view function it currently fails to use this functionality on the magic contract. This is giving some issues with some dApp deployments that use this functionality including `multicall`.

**Comment by fijter** [comment]
Issue has nothing to do with gasleft() perse but more with calling transactional functions as view functions which is currently not always possible when using the magic contracts.

**Comment by dessaya** [comment]
Changing `eth_call` to allow calling non-view functions (discarding state changes) might solve the issue.
