### ISSUE TITLE
Token approvement on native and base tokens is limited to uint64

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#2112]
It seems like that the current approve limit of ERC20BaseTokens.sol and ERC20NativeTokens.sol is limited to MAX_UINT64

```
require(numTokens <= MAX_UINT64, "amount is too large");
```
Is it possible to remove that limit and align it to the somehow more standard limit of max_uint_256?

**Comment by fijter** [comment]
Leave BaseToken as is (can't be > UINT64 anyway), and a check can be removed for NativeTokens, potentially a workaround for the approval allowance of UINT256.
