### ISSUE TITLE
Allow "0 fee" execution

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp-legacy#2119]
Right now setting the gasPerToken to 0:0 will mean nothing can be payed for. 
We can add an edge case to make running requests "free" (0 fees).

Should be documented that its not something we recommend and doesn't make sense on public networks. However it might be potentially useful for "private" chains where access is restricted.

**Comment by dessaya** [comment]
Are you sure that 0:0 can be set? I'm pretty sure that if the use attempts to set 0:0 the request is rejected.

**Comment by jorgemmsilva** [comment]
No, I didn't actually try it. Cool that we have a check in place

**Comment by howjmay** [comment]
@jorgemmsilva I have tried. As my PR. `gasPerToken` is not allowed to be set to 0:0. If I didn't understand wrong, this issue aims to allow free request (zero gas fee) when the `gasPerToken` is set to 0:0?
