### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by andreapabong** [iotaledger/wasp-legacy#2135]
**Describe the bug**
I can not to make build.

**To Reproduce**
1. Download the repository
2. open a terminal and run: make build 

Error:
make build
cd packages/vm/core/evm/iscmagic && go generate
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
cd packages/evm/evmtest && go generate
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
   --> ISCTest.sol:162:9:
    |
162 |         selfdestruct(beneficiary);
    |         ^^^^^^^^^^^^

Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
Compiler run successful. Artifact(s) can be found in directory ".".
cd tools/wasp-cli && go mod tidy && go build -ldflags "-X=github.com/iotaledger/wasp/core/app.Version=v0.5.1-alpha.1-123-g909ae1888" -o ../../
# github.com/iotaledger/wasp/packages/wasmvm/wasmhost
../../packages/wasmvm/wasmhost/wasmtimevm.go:14:23: undefined: wasmtime.Engine
../../packages/wasmvm/wasmhost/wasmtimevm.go:15:23: undefined: wasmtime.Instance
../../packages/wasmvm/wasmhost/wasmtimevm.go:16:23: undefined: wasmtime.Linker
../../packages/wasmvm/wasmhost/wasmtimevm.go:17:23: undefined: wasmtime.Memory
../../packages/wasmvm/wasmhost/wasmtimevm.go:18:23: undefined: wasmtime.Module
../../packages/wasmvm/wasmhost/wasmtimevm.go:19:23: undefined: wasmtime.Store
../../packages/wasmvm/wasmhost/wasmtimevm.go:25:21: undefined: wasmtime.NewConfig
../../packages/wasmvm/wasmhost/wasmtimevm.go:28:37: undefined: wasmtime.NewEngineWithConfig
../../packages/wasmvm/wasmhost/wasmtimevm.go:80:22: undefined: wasmtime.NewStore
../../packages/wasmvm/wasmhost/wasmtimevm.go:81:23: undefined: wasmtime.NewLinker
../../packages/wasmvm/wasmhost/wasmtimevm.go:81:23: too many errors
make: *** [Makefile:33: build-cli] Error 1

----------------------
go version
go version go1.20.2 linux/amd64
-----
wasmtime -V
wasmtime-cli 6.0.1
--------------

**Comment by jorgemmsilva** [comment]
you need to do `make wasm` before.
but why exactly do you need to build wasp? It its recommended that you use the docker image we provide for a better experience

**Comment by andreapabong** [comment]
Thank you, Jorge.
I am trying to build wasp in order to use wasp-cluster. 
After make build I have wasp, wasp-cli and wasp-cluster.
But when I try:
wasp-cluster init ./cluster/
non-disposable cluster and privtangle are mutually exclusived.

could you help me out? 
Thank you

**Comment by IliasElabbassi** [comment]
> 2. open a terminal and run: make build
> 
> Error: make build cd packages/vm/core/evm/iscmagic && go generate Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". cd packages/evm/evmtest && go generate Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended. --> ISCTest.sol:162:9: | 162 | selfdestruct(beneficiary); | ^^^^^^^^^^^^
> 
> Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". Compiler run successful. Artifact(s) can be found in directory ".". cd tools/wasp-cli && go mod tidy && go build -ldflags "-X=github.com/iotaledger/wasp/core/app.Version=v0.5.1-alpha.1-123-g909ae1888" -o ../../
> 
> # github.com/iotaledger/wasp/packages/wasmvm/wasmhost
> ../../packages/wasmvm/wasmhost/wasmtimevm.go:14:23: undefined: wasmtime.Engine ../../packages/wasmvm/wasmhost/wasmtimevm.go:15:23: undefined: wasmtime.Instance ../../packages/wasmvm/wasmhost/wasmtimevm.go:16:23: undefined: wasmtime.Linker ../../packages/wasmvm/wasmhost/wasmtimevm.go:17:23: undefined: wasmtime.Memory ../../packages/wasmvm/wasmhost/wasmtimevm.go:18:23: undefined: wasmtime.Module ../../packages/wasmvm/wasmhost/wasmtimevm.go:19:23: undefined: wasmtime.Store ../../packages/wasmvm/wasmhost/wasmtimevm.go:25:21: undefined: wasmtime.NewConfig ../../packages/wasmvm/wasmhost/wasmtimevm.go:28:37: undefined: wasmtime.NewEngineWithConfig ../../packages/wasmvm/wasmhost/wasmtimevm.go:80:22: undefined: wasmtime.NewStore ../../packages/wasmvm/wasmhost/wasmtimevm.go:81:23: undefined: wasmtime.NewLinker ../../packages/wasmvm/wasmhost/wasmtimevm.go:81:23: too many errors make: *** [Makefile:33: build-cli] Error 1
> 

Hi i had the same error a few days ago.
I just had to run this commands before installing wasp, since I was running a new WSL instance on Ubuntu22.04.2 :
```
sudo apt-get update
sudo apt install build-essential
```

then you can run `make install` , if you already have all the other dependencies instaled (go, rust, solidity compiler ...) I believe.

and then 

```
make wasm
make build-cli
```

Hope this help .

**Comment by jorgemmsilva** [comment]
@andreapabong you shouldn't use wasp-cluster, just try the local-setup. 
The cluster tool is only used for the team to run tests internally
