### ISSUE TITLE
improve cross-chain "withdrawal/deposit"

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp-legacy#2177]
basically this line:

https://github.com/iotaledger/wasp/blob/develop/packages/vm/core/accounts/impl.go#L107

when depositing funds to another chain you need to call tranferAllowanceTo , this means that if the call fails (for example due to not enough fees), the deposit will not go to the target account, but instead stay on the "original chain account" on the "target chain"
the messed up part is that the cost of that request is unknown (because the target chain might have high fees, but we have no way to know). I think the best way to address this is actually to let the caller specify a "target chain fee amount", so that the caller is responsible for specifying a value that won't fail

**Comment by howjmay** [comment]
The codebase has changed. The line mentioned here should be https://github.com/iotaledger/wasp/blob/9b2aecccbd0f86a113b7ad259813eaef55d177bf/packages/vm/core/accounts/impl.go#LL108C17-L108C37
