### ISSUE TITLE
Add a --ignore-self flag for `peering import-trusted` so the single json file can be batch applied to many nodes without having to edit it all the time

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2180]
You can export the list of peers and import it again on other nodes, however it fails if that node is in the list itself. It's maybe better to allow this and fully ignore the self-added host over throwing an error, given I have to modify the json file every time to exclude the self reference kind of defeating the purpose of the import/export functionality.

**Comment by fijter** [comment]
Also maybe an option to change the default 'me' and provide a peering URL for the initial node you are exporting for

**Comment by lmoe** [comment]
Also extend the test somewhere in https://github.com/iotaledger/wasp/blob/develop/tools/cluster/tests/wasp-cli_test.go#L519
