### ISSUE TITLE
Access nodes don't allow subscription to EVM events, committee nodes do

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2254]
```{"jsonrpc":"2.0","id": 1, "method": "eth_subscribe", "params": ["logs", {"topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}]}```

This works on the testnet committee nodes, not on the access nodes 🤔

**Comment by kape1395** [comment]
Is it still the case?

**Comment by fijter** [comment]
Need to recheck

**Comment by shufps** [comment]
We checked on our backup-node that - it seems to be working. We are receiving events now :partying_face:
