### ISSUE TITLE
Approve MAX_UINT256 for 0x1074010000000000000000000000000000000000 reverts

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#2390]
Approving MAX_UINT256 on 0x1074010000000000000000000000000000000000 reverts with 'amount is too large'

This is potentially similar to #2112

**Comment by dessaya** [comment]
This is as intended. The base tokens on L1 and L2 is an `uint64` amount, so it does not make sense to approve more than that.

**Comment by 2013anghel** [comment]
same smr testnrt

**Comment by 2013anghel** [comment]
0x70FBd71957cf9E1d72d1E26fb8C7C1a997e143A6

**Comment by dahof1** [comment]
It breaks the compatiblity for evm contracts which coming from other chains. For example there a lot of contracts which doing internal a (safe)Approve to MAX_UINT_256 to safely work and transact further the token (usdc, usdt, btc... no matter how many decimals). 

In the above case we have to check explicitly if the token is SMR and then approve to MAX_UINT_64. So am just voting for a better evm compatatibility

So without the explicit limit in the approve what could be the worst case? I assume any transaction with an amount greater 1 << 64 -1 will fail anyhow

**Comment by MoonLabsDev** [comment]
The intention should be EVM compability. even if you cant approve more, you force battleproved code to be changed JUST for 1 token. for all other tokens it will still work. You will force THOUSANDS of Devs to write an extra safe approve function that always approves the given amount EXCEPT if they use wSMR 

maybe check
if (amount > MAX_UINT_64)
 approve(MAX_UINT_64)

**Comment by 2013anghel** [comment]
tanks

**Comment by jorgemmsilva** [comment]
accepting MAX_UINT256, but capping to the current user balance seems like a good idea, so that someone can't "allow to take all SMR from my account forever"

**Comment by MoonLabsDev** [comment]
Please open it again and change code to

```
if !numTokens.IsUint64() {
            // Calling approve(MAX_UINT256) is semantically equivalent to an "infinite" allowance
            if numTokens.Cmp(gethmath.MaxBig256) == 0 {
                numTokens = big.NewInt(0).SetUint64(math.MaxUint64)
            } else {
                panic("base tokens amount must be an uint64")
            }
        }
        allowance.BaseTokens = numTokens.Uint64()
```

would be better if you change it to
```
if numTokens.Cmp(gethmath.MaxBig64 >= 0 {
                numTokens = big.NewInt(0).SetUint64(math.MaxUint64)
}
```

and even better if for the native shimmer you also clamp it to current balance for security (steal infinite gas issue)
