### ISSUE TITLE
Python web3py does not yet support event handling / filtering

### ISSUE THREAD

**Issue by github-i286** [iotaledger/wasp-legacy#2439]
**Describe the bug**
The Python web3 library (https://web3py.readthedocs.io/en/stable/) implements generally SC event APIs like w3.eth.filter or contract_instance.events.<my event naeme>.create_filter(...).

The wasp/evmproxy however raises a error like when try to call these functions:
A) web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method eth_newPendingTransactionFilter does not exist/is not available'}
B) web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method eth_newFilter does not exist/is not available'}

Tested with tested API 6.2.0

**To Reproduce**
create a smart contract object on Pythin with web3 library, and try to catch or filter events from a smart contract.

Sample code:
1. deploy a EVM / Solidity contract with an event like

event <my event name>(bytes32 hash, address executor, address previousOwner, address newOwner);

2 Create Python code like:
import web3
w3 = web3.Web3(web3.HTTPProvider('https://json-rpc.evm.testnet.shimmer.network/'))
contract_instance = w3.eth.contract(address=<contract address>, abi=<contract abi>)
myfilter = contract_instance.events.<my event name>.create_filter(fromBlock='latest')

it fails on the last statement with 'code': -32601, 'message': 'the method eth_newFilter does not exist/is not available

**expected behavior**
web3py with ShimmerEVM should implement SC event-functions.

**Network and versioning**
 - Type of L1 network: Shimmer Testnet
 - Type of Wasp chain: ShimmerEVM Testnet
 - Interaction method: web3py
 - Interaction software: web3py
 - Version of Wasp: unknown

**Evironment information**
Tranasaction interaction with the smart contract like w3.eth.send_raw_transaction(signed_tx.rawTransaction) all works well.

**Comment by jorgemmsilva** [comment]
this has been opened for a while. We have made a lot of improvements since, and I don't see reports of mismatching functionality with ethereum client tools for now. Please re-open if this still applies
