### ISSUE TITLE
Publish @iscmagic on npmjs.org

### ISSUE THREAD

**Issue by huhn511** [iotaledger/wasp-legacy#2441]
To improve the DX, we should publish the @iscmagic contacts to npmjs.org so developers can easily install them with

`npm install @iscmagic`

and use them in their code.

**Comment by Crelde** [comment]
Looks like something like this is up an running now: 
https://www.npmjs.com/package/iscmagic

Just looks like it creates a folder cllaed "iscmagic" rather than "@iscmagic" which the sol files in the folder refer to.
