### ISSUE TITLE
Very high continuous writing speed to rocksdb but database grows slowly

### ISSUE THREAD

**Issue by shufps** [iotaledger/wasp-legacy#2467]
We observed at avg a writing speed of 138MB/s, but the database grows only 20GB daily.

![image](https://github.com/iotaledger/wasp/assets/3079832/8c63cb92-13e9-4d4c-a392-10846861a902)

There is about a factor of x600 between written (~12TB/day) and effectively stored (~20GB/day) data.

We also see, that compaction is running almost each minute what probably is the reason why we don't see that much database growth.

We suspect that duplicate data (or perhaps a lot of data is stored with the same key, thus overwriting old data?) is written a lot what could explain why compaction is so successful.

(Additionally, we noticed, that about ~28% of CPUs is used by rocksdb).

**Comment by shufps** [comment]
I see a (very) worrying tendency on disk utilization:

![image](https://github.com/iotaledger/wasp/assets/3079832/27e3697d-a4be-40c9-998d-a1b5b7595bd5)

**Comment by fijter** [comment]
Metrics to be added, then it can close, expected behavior.

**Comment by fijter** [comment]
Metrics adding needs a fork of RocksDB, and already in RocksDB log, too much work to do this for a nice to have.
