### ISSUE TITLE
@iscmagic npm package as part of the deploy flow

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2470]
The iscmagic contracts are not easy to import/use right now, you need to fetch them from the repo in some folder you have to know about, download and copy them to your working folder. Can we setup a deploy flow maybe that on every new version will deploy a new npm package containing these `.sol` files?

**Comment by luke-thorne** [comment]
Still need to add better docs for using the npm package.

**Comment by fijter** [comment]
Awaiting breaking release
