### ISSUE TITLE
Returned block timestamp not equal to L2 block confirmation time

### ISSUE THREAD

**Issue by adrian-grassl** [iotaledger/wasp-legacy#2471]
**Describe the bug**
The returned block timestamps seem to be derived from the last seen L1 milestone, even though this timestamp has nothing to do with the actual time a block was successfully attached and its included transactions confirmed. Below is an example from ShimmerEVM Testnet, which shows that multiple blocks, which were confirmed independently from each other, partially inherit the same timestamp of the recent L1 milestone, which creates those "batches" of blocks with the exact same timestamp.

```
Block 2030289 issued with 10 transaction(s) at 2023-05-12T14:31:08.000Z.
Block 2030290 issued with 15 transaction(s) at 2023-05-12T14:31:08.000Z.
Block 2030291 issued with 12 transaction(s) at 2023-05-12T14:31:08.000Z.
Block 2030292 issued with 12 transaction(s) at 2023-05-12T14:31:08.000Z.
Block 2030293 issued with 15 transaction(s) at 2023-05-12T14:31:08.000Z.

Block 2030294 issued with 15 transaction(s) at 2023-05-12T14:31:13.000Z.
Block 2030295 issued with 15 transaction(s) at 2023-05-12T14:31:13.000Z.
Block 2030296 issued with 8 transaction(s)  at 2023-05-12T14:31:13.000Z.
Block 2030297 issued with 10 transaction(s) at 2023-05-12T14:31:13.000Z.
Block 2030298 issued with 9 transaction(s)  at 2023-05-12T14:31:13.000Z.
Block 2030299 issued with 20 transaction(s) at 2023-05-12T14:31:13.000Z.
Block 2030300 issued with 13 transaction(s) at 2023-05-12T14:31:13.000Z.

Block 2030301 issued with 11 transaction(s) at 2023-05-12T14:31:18.000Z.
Block 2030302 issued with 7 transaction(s)  at 2023-05-12T14:31:18.000Z.
Block 2030303 issued with 10 transaction(s) at 2023-05-12T14:31:18.000Z.
```

**To Reproduce**
Any ISC EVM chain has this behavior and the higher the L1 milestone interval the more obvious the time offset between returned block timestamp and actual confirmation time on L2.

**Expected behavior**
The block timestamp should be as close to the time of actual confirmation as possible.

**Network and versioning**
 - Any Wasp (EVM) chain

**Comment by jorgemmsilva** [comment]
closing as this will change soon with iota2.0 anyway
