### ISSUE TITLE
OOM caused by gossip/peering

### ISSUE THREAD

**Issue by shufps** [iotaledger/wasp-legacy#2475]
We saw OOM problems that seem to be connected to Gossip:

![image](https://github.com/iotaledger/wasp/assets/3079832/8791523f-2b71-44c6-84eb-35ea6cc466dc)

It seems that the receiving Buffer has a maximum size (set to 10000) that could overflow.

https://github.com/iotaledger/wasp/blob/develop/packages/peering/lpp/lpp_peer.go#L57

To consume this amount of memory, messages would need to be very big (in avg at least 700kB+) what sounds unplausible.

**Comment by fijter** [comment]
Can not reproduce right now without a lot of spam, need to test again with a massive spam session later on.
