### ISSUE TITLE
Get Test Tokens

### ISSUE THREAD

**Issue by adriandavidenco** [iotaledger/wasp-legacy#2479]
**Describe the bug**

**To Reproduce**
We can only investigate bug reports that can easily be reproduced and all information needed to reproduce this issue has been supplied with this issue. Please provide the steps to reproduce this issue in the easiest way possible:

1. Deploy contract X '...'
2. Interact with Contract X by calling method Y '....'
3. See error
![Снимок экрана (11)](https://github.com/iotaledger/wasp/assets/133808498/2e328211-23f1-4143-a106-4b3736f5b903)

**Expected behavior**

**Screenshots**

**Network and versioning**
 - Type of L1 network: [e.g. Shimmer Testnet, Shimmer, Private Tangle, IOTA Mainnet]
 - Type of Wasp chain: [e.g. Private chain, ShimmerEVM Testnet, ShimmerEVM]
 - Interaction method: [e.g. Wasp-cli, JSON/RPC HTTP, JSON/RPC Websocket, Wasp API, Dashboard]
 - Interaction software: [e.g. Metamask, wasp-cli, hardhat, API]
 - Version of Wasp [e.g. 0.6.0]

**Additional context**

**Comment by jorgemmsilva** [comment]
please use: https://evm-toolkit.evm.testnet.shimmer.network/
