### ISSUE TITLE
Revisit of nonce implementation

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2517]
Nonces should ideally be sequential, which they are currently not for ISC; Should be consistent with the nonces on the EVM chain. Making this consistent and sequential should help with preventing replay attacks with pruning enabled and could contribute to not being able to have multiple pending transactions on the EVM chain with the same account.

**Comment by jorgemmsilva** [comment]
found an issue where ISC/EVM nonces can get out-of-sync when an EVM request fails. This is relevant because the mempool currently only checks the ISC nonce.

**Comment by fijter** [comment]
@jorgemmsilva is this still relevant?
