### ISSUE TITLE
Rotation with maintenance mode not working correctly

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2605]
When trying to `rotate-with-dkg` it uses maintenance mode by default, but with this flag enabled it always seems to result in a conflict error:

```
2023-06-15T11:10:04+02:00	INFO	nc	Posted blockID 0x8c34ab08feb0fc45f0de2da22844e66bb04eacf3ec167759c7052070d008ed29
2023-06-15T11:10:04+02:00	INFO	nc	Posted transaction id 0x5021da21ec02849b492feb62d711d4e0e1de39870761700102fb7ce41128dcd9
2023-06-15T11:10:17+02:00	INFO	nc	Posted blockID 0xa3a149bb3fc57648b4b2ac4c8cb2cdacbc446ba27c633307536ca7fe457050cd
2023-06-15T11:10:17+02:00	INFO	nc	Posted transaction id 0xe6eb8b9d049c11854cce85c565315421a58dbecf2cc8dda44f165bc2b73524bb
Posted on-ledger transaction 0xe6eb8b9d049c11854cce85c565315421a58dbecf2cc8dda44f165bc2b73524bb containing 1 request:
  - #0 (check result with: ./wasp-cli chain request 0xe6eb8b9d049c11854cce85c565315421a58dbecf2cc8dda44f165bc2b73524bb0000)
Waiting for tx requests to be processed...
panic: block was not included in the ledger. IsTransaction: true, LedgerInclusionState: conflicting, ConflictReason: 1

goroutine 1 [running]:
github.com/iotaledger/wasp/tools/wasp-cli/chain.rotateTo({0xc0008881a0, 0x7}, {0x2f4f410, 0xc0008e2640})
```

When skipping it it works as intended but ideally this should just work ;)

Also: help text is a duplication of quorum for the `--skip-maintenance` flag:
```
      --quorum int         quorum (default: 3/4s of the number of committee nodes)
      --skip-maintenance   quorum (default: 3/4s of the number of committee nodes)
```

Tested on a new fresh node setup going from single node committee to 5/7 committee using 0.7.0-alpha.1

**Comment by jorgemmsilva** [comment]
this is due to the maintenance tx conflicting with the "rotation tx" (double spend).
the indexer takes some (unknown) amount of time to update

I've changed to send the maintenance request as off-ledger by default here: https://github.com/iotaledger/wasp/pull/2782
that should fix this issue, unless the user forces on-ledger requests to be used
