### ISSUE TITLE
webapi broken error responses

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp-legacy#2625]
getting some weird "invalid jsons" that are just duplicated body responses:
```
{"Message":"Not Found","Error":""}
{"Message":"Not Found","Error":""}
```
or
```
{"Message":"token is invalid","Error":""}
{"Message":"token is invalid","Error":""}
```

not sure where this is coming from, but besides being wrong makes the wasp-cli spew some unhelpful messages:
```
error: invalid character '{' after top-level value
```

**Comment by fijter** [comment]
Hornet related, revisit after new release

**Comment by lmoe** [comment]
The error handler just didn't always consider, if a response was already committed. Therefore it sent those twice.
