### ISSUE TITLE
I can't compile ISCMagic contracts

### ISSUE THREAD

**Issue by LaKabra** [iotaledger/wasp-legacy#2687]
**Describe the bug**

[Problem 1: Incorrect path of import on the ISCMagic contracts](https://discord.com/channels/397872799483428865/930642258427019354/1126876924833169458): I am unable to compile the test example of ISC on hardhat, all the imports of the ISCMagic contracts seem wrong, when tryng to correct the paths and recompile I get stack to deep error.

[¿Possible cause of "stack too deep error"?](https://discord.com/channels/397872799483428865/930642258427019354/1126888847146487818)

Problem 2: Regardless of the problem 1, the evm bytecode contract for the end user would still be too large, it will continue to import all the recursive imports of the associated contracts, explained [here](https://discord.com/channels/397872799483428865/930642258427019354/1126921882449494078) @luke-thorne

**To Reproduce**

1 - Make a contract with code example "calling getEntropy()" following the instructions of the [wiki]((https://wiki.iota.org/shimmer/smart-contracts/guide/evm/magic/)):

2 - Try compile with hardhat

**Screenshots**
**All images are available on discord at the links mentioned above.**

**Comment by LaKabra** [comment]
To simplify and clarify the second problem

For example, if I want to get random numbers, I have to call ISC.sandbox so I import ISC.sol, so consequently I have all the ISCMagic contracts imported in an 8 lines contract from which I only want to get a random number:

```
pragma solidity >=0.8.5;

-> this import
import "@iota/iscmagic/ISC.sol";
-> ==
import "./ISCSandbox.sol"; + import "ISCTypes.sol"
import "./ISCAccounts.sol"; + import "ISCTypes.sol"
import "./ISCUtil.sol"; + import "ISCTypes.sol"
import "./ISCPrivileged.sol"; + import "ISCTypes.sol"
import "./ERC20BaseTokens.sol"; + import ISCTypes, ISCSandbox, ISCPrivileged, ISCAccounts;
import "./ERC20NativeTokens.sol"; + import ISCTypes, ISCSandbox, ISCAccounts,ISCPrivileged;
import "./ERC721NFTs.sol"; + import ISCTypes, ISCSandbox, ISCAccounts,ISCPrivileged;
import "./ERC721NFTCollection.sol"; + import ISCTypes, ISCSandbox, ISCAccounts,ISCPrivileged, ERC721NFTs;

== ¿stack too deep?

contract MyEVMContract {
event EntropyEvent(bytes32 entropy);

// this will emit a "random" value taken from the ISC entropy value
function emitEntropy() public {
    bytes32 e = ISC.sandbox.getEntropy();
    emit EntropyEvent(e);
}
```

Regardless of whether I import selectively in all ISCMagic contracts, example ISC.sol

```
import {ISCSandbox, __iscSandbox} from "./ISCSandbox.sol"; // importa isctypes, lo requiere ISCSandbox.sol
import {ISCAccounts, __iscAccounts} from "./ISCAccounts.sol"; // importa isctypes
import {ISCUtil, __iscUtil} from "./ISCUtil.sol"; // importa isctypes
// import {ISCPrivileged} from "./ISCPrivileged.sol"; // importa isctypes
import {ERC20BaseTokens, __erc20BaseTokens} from "./ERC20BaseTokens.sol"; // importa isctypes+accounts+sandbox+privileged
import {ERC20NativeTokens} from "./ERC20NativeTokens.sol"; // importa isctypes+sandbox+accounts+privileged
import {ERC721NFTs, __erc721NFTs} from "./ERC721NFTs.sol"; // importa isctypes+sandbox+accounts+privileged
import {NFTID, ERC721NFTCollection} from "./ERC721NFTCollection.sol"; // importa isctypes+sandbox+accounts+privileged+erc721
```

I would still inherit all the interleaved code that I am not going to use with what I will get + bytecode + gas costs when interacting with ISCMagic.

In my opinion each library, function, interface should be able to interact independently to be able to adapt to the needs of each project "minimalist calls", without dragging unnecessary code, this facilitates the interaction with the developer and saves a lot of unnecessary load bothering the network in every interaction with ISCMagic.

**Comment by LaKabra** [comment]
The option that comes to mind is to have all the functions in isolated packages according to their type (ERC20, ISC, ERC721 etc..) to be able to be called publicly in such a way that no package contains code inherited from another package, so you make sure that even the packages do not drag unnecessary code from other packages in the execution of the call.

createFoundry, createToken, getEntropy with interfaces

```
    -- MyFile.sol --

    address constant PKG_ERC20 = 0x1074000000000000000000000000000000000000; // example
    address constant PKG_ISC = 0x1074000000000000000000000000000000000000; // example

    interface ISCERC20 {
        function foundryCreateNew(NativeTokenScheme memory tokenScheme, ISCAssets memory allowance) external returns(uint32);
    }

    interface RandomNumber {
        function getEntropy() external view returns (bytes32);
    }

    function getRandom() {
        bytes32 e = RandomNumber(PKG_ISC).getEntropy();
    }

    function createFoundry() {
        ISCERC20(PKG_ERC20).foundryCreateNew(
            tokenScheme, 
            getAllowance(storageDeposit)
        );
    }

    function createToken() {
        ERC20Data(CORE).registerERC20NativeToken(
            f, 
            name, 
            symbol, 
            decimals, 
            getAllowance(storageDeposit)
        );
    }

    --
```

**Comment by luke-thorne** [comment]
@LaKabra do these work for you with [`"@iota/iscmagic": "^0.7.0-alpha.8"`](https://www.npmjs.com/package/@iota/iscmagic)?
You can import the specific file directly and use it in your file. I can't reproduce the stack too deep error on my end. Both of these work for me:

## Minimal imports

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity >=0.8.5;

import "@iota/iscmagic/ISCSandbox.sol";

contract MyEVMContract {
    event EntropyEvent(bytes32 entropy);

    // this will emit a "random" value taken from the ISC entropy value
    function emitEntropy() public {
        bytes32 e = __iscSandbox.getEntropy();
        emit EntropyEvent(e);
    }
}
```

## Copied from the wiki

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity >=0.8.5;

import "@iota/iscmagic/ISC.sol";

contract MyEVMContract {
    event EntropyEvent(bytes32 entropy);

    // this will emit a "random" value taken from the ISC entropy value
    function emitEntropy() public {
        bytes32 e = ISC.sandbox.getEntropy();
        emit EntropyEvent(e);
    }
}
```

**Comment by LaKabra** [comment]
Yes, it works also in previous versions, apparently the stack too deep is produced when optimizer is enabled, tested 0.7.0-alpha.6 and 0.7.0-alpha.8.

```
solidity: {
    compilers: [{
            version: "0.8.19",
            settings: {
                optimizer: {
                    enabled: false,
                    runs: 200,
                },
            },
      }]
  }
```

**Comment by LaKabra** [comment]
This conditions to the projects to have to create different "mini" contracts that interact with the main contract as an interface.

So, at this point, I can launch contracts without interacting with ISC with the optimizer enabled but if I want to interact with ISC I can only deploy a "mini" contracts without going over the limit.

`Warning: The contract code size is 41268 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon).`

`Deploy: ProviderError: max code size exceeded`

Which leads me to think that the main problem (for me) is resolving the "stack too deep" for the optimizer can do his job:

> The option that comes to mind is to have all the functions in isolated packages according to their type (ERC20, ISC, ERC721 etc..) to be able to be called publicly in such a way that no package contains code inherited from another package, so you make sure that even the packages do not drag unnecessary code from other packages in the execution of the call.
> 
> createFoundry, createToken, getEntropy with interfaces
> 
> ```
>     -- MyFile.sol --
> 
>     address constant PKG_ERC20 = 0x1074000000000000000000000000000000000000; // example
>     address constant PKG_ISC = 0x1074000000000000000000000000000000000000; // example
> 
>     interface ISCERC20 {
>         function foundryCreateNew(NativeTokenScheme memory tokenScheme, ISCAssets memory allowance) external returns(uint32);
>     }
> 
>     interface RandomNumber {
>         function getEntropy() external view returns (bytes32);
>     }
> 
>     function getRandom() {
>         bytes32 e = RandomNumber(PKG_ISC).getEntropy();
>     }
> 
>     function createFoundry() {
>         ISCERC20(PKG_ERC20).foundryCreateNew(
>             tokenScheme, 
>             getAllowance(storageDeposit)
>         );
>     }
> 
>     function createToken() {
>         ERC20Data(CORE).registerERC20NativeToken(
>             f, 
>             name, 
>             symbol, 
>             decimals, 
>             getAllowance(storageDeposit)
>         );
>     }
> 
>     --
> ```

**Comment by luke-thorne** [comment]
I get the stack too deep error when importing the full ISC.sol contract so I'll work through what is going on there. 

In the meantime, I don't get that error when I use the minimized import, does importing your specific use case work?
For example:
```solidity
import "@iota/iscmagic/ISCSandbox.sol";
...
  __iscSandbox.getEntropy();
...
```

**Comment by LaKabra** [comment]
Yes, with the minimized import it works but note that ISCSandbox.sol does not have recursive imports, it only imports ISCTypes.sol and ISCTypes.sol does not import anything so it does not exceed the code limit.

**Comment by luke-thorne** [comment]
Sweet. Thanks! Just making sure we are working from the same assumptions. We are working to resolve the recursive imports.

**Comment by luke-thorne** [comment]
@LaKabra it comes from the ISCAssets struct having 2 dynamic arrays which would be a significant change. Does compiling with `--via-ir` or `solidity.settings.viaIR: true` in your hardhat config work?

**Comment by LaKabra** [comment]
```
 solidity: {
        compilers: [{
                version: "0.8.21",
                settings: {
      		viaIR: true,
                optimizer: {
                     enabled: true,
                     runs: 200,
```
Works
