### ISSUE TITLE
limitation of getEntropy()

### ISSUE THREAD

**Issue by LaKabra** [iotaledger/wasp-legacy#2746]
Currently I cannot get unique and individual results in an array calling getEntropy() in the same transaction because the state of getEntropy is not updated until the transaction has finished, this forces to the user to make a new calls if the user wants new numbers which makes scalable usability of getEntropy() impossible.

In my case, I need to extract as many numbers as the user wants, if the user wants 100 numbers, I want to be able to make 100 calls to getEntropy() and extract the numbers from each call to assign them to the user.

```
pragma solidity ^0.8.0;

contract testView {

    uint256 public a;

    function viewThis() external returns (uint256) {
        a++;
        return a;
    }

    function Address() external view returns (address) {
        return address(this);
    }
}

import "@iota/iscmagic/ISC.sol";

interface iTest {
    function viewThis() external returns (uint256);
}

contract testCalls {

    event cc(bytes[]);
    event pp(uint256[]);
    event tt(bytes32[]);

    uint256 sum;

    function testSum() public returns (uint256) {
        sum++;
        return sum;
    }

    // works
    function callTest() external {
        uint256[] memory ui = new uint256[](3);

        for (uint256 a; 3>a; a++) {
            ui[a] = testSum();
        }

        emit pp(ui);
    }

    // not working, duplicated
    function callTest2() external {
        bytes[] memory rt = new bytes[](3);

        for (uint256 a; 3>a; a++) {

            (, rt[a]) = address(
                ISC.sandbox
            ).call(abi.encodeWithSignature("getEntropy()"));

        }
        emit cc(rt);
    }

    // not working, duplicated
    function callTest3() external {
        bytes32[] memory rt = new bytes32[](3);

        for (uint256 a; 3>a; a++) {
            rt[a] = ISC.sandbox.getEntropy();
        }

        emit tt(rt);
    }

    // Works
    function callTest4(address t) external {
        uint256[] memory rt = new uint256[](3);

        for (uint256 a; 3>a; a++) {
            rt[a] = iTest(t).viewThis();
        }

        emit pp(rt);
    }

    // works
    function callTest5(address t) external {
        bytes[] memory rt = new bytes[](3);

        for (uint256 a; 3>a; a++) {
           (, rt[a]) = address(t).call(abi.encodeWithSignature("viewThis()"));
        }

        emit cc(rt);
    }
}
```

**Comment by jorgemmsilva** [comment]
you're meant to use the entropy as a seed to a random number generator

**Comment by fijter** [comment]
As Jorge said, the entropy is supposed to be used to generate random numbers and is deterministic per block. Closing this issue.

**Comment by LaKabra** [comment]
isn't it the same? if I use 1 entropy to generate 100 seeds per block or timestamp the result could not be predictable or repetitive?

**Comment by fijter** [comment]
This is how randomness usually works, you have an entropy source which is then used to generate randomness based on that entropy. This way the randomness is deterministic, you will always get the same values as long as the 'seed' (entropy) is the same (which is something we need given we need to validate the results on multiple nodes, if the random values differ per node the state is not the same). What you need to do with this entropy is generate random numbers based on it and some other value, like an index (1,2,3,4, etc.) - The entropy is only known after consensus is reached so the actual random numbers are not known until a state is reached where no new transactions can be added to a block anymore. I will open a new Issue to add a helper for this to our standard contracts to make this more approachable given the randomness function needs to be implemented properly, but you can already do this randomness yourself by implementing such a function that takes the entropy and an index and generates as many random numbers as you'd like.

**Comment by fijter** [comment]
https://github.com/iotaledger/wasp/issues/2747 FYI, you can look at the approach linked there and apply it yourself for now given this issue does not have the highest priority for us to implement at this point of time, it's a nice to have :)
