### ISSUE TITLE
Unable to get matching addresses in Wasp-CLI and Firefly/CLI-Wallet

### ISSUE THREAD

**Issue by DiePutze5853** [iotaledger/wasp-legacy#2966]
Hello,

I wanted to test the `wasp-cli register-erc20-native-token` .

Since wasp-cli doesn't have any means to create alias and foundry outputs I tried to create them in Firefly/Iota-SDK/CLI-Wallet, but I am unable to get those wallets into the wasp-cli.
I wrote a small python script to generate a mnemonic and convert it to a hex-seed:

```
from iota_sdk import Utils

# Generate a random BIP39 mnemonic
mnemonic = Utils.generate_mnemonic()
print(mnemonic)
mnemonic2hex = Utils.mnemonic_to_hex_seed(mnemonic)
print(mnemonic2hex)

```

Here is an example output:
trial almost ten feature wage enroll patch decline pond cloth frost report horse mobile glove hip carpet make 
empty text total wrap dish sponsor

0x417d745c967897a47e473334bb639843e7ffb7d7e80f4113489cf3a865a8447de07efe54e4f52794029476dbbda99654ae196995912b16deb148895f3c378134

My wasp-cli.json looks like this:
```
{
  "l1": {
    "apiaddress": "http://localhost:14265",
    "faucetaddress": "http://localhost:8091"
  },
  "wallet": {
    "seed": "0x417d745c967897a47e473334bb639843e7ffb7d7e80f4113489cf3a865a8447de07efe54e4f52794029476dbbda99654ae196995912b16deb148895f3c378134"
  },
  "wasp": {
    "0": "http://localhost:9090"
  }
}
```

When I call `wasp-cli address` i get this address:
Address index: 0
  Address: tst1qpyk2fkvyrtjw9kmn7hgf85x6jvgj0t8gvvznvwaemwvz2a0xh296jq6tae

When I import the mnemonic in Firefly for example I'm getting this address:
tst1qzxruatwthlkcgsyxqdn96ssdf9z3f80rm0gam5aklzt68l9eg22zhu5zpn

Requesting funds from the faucet and then using the balance finder in Firefly doesn't find the wasp-cli address either.

Any hints on what I'm doing wrong would be appreciated.

**Comment by jorgemmsilva** [comment]
Thank you for raising this issue. I'm investigating how we can align and use the same sub-seed generation as Firefly.

As an alternative to mint tokens on your local-setup, you can use wasp-cli to interact with the `accounts` core contract to:
 - [create a new foundry](https://wiki.iota.org/wasp-evm/reference/core-contracts/accounts/#foundrycreatenewt-tokenscheme-s-serialnumber)
- [mint new tokens](https://wiki.iota.org/wasp-evm/reference/core-contracts/accounts/#foundrymodifysupplys-serialnumber-d-supplydeltaabs-y-destroytokens) 

Then you can use the `register-erc20-native-token` function because the foundry is already known to the chain

**Comment by DiePutze5853** [comment]
Thanks for the response @jorgemmsilva , Will try that for the time being!

I've seen this pull request by @lmoe (https://github.com/iotaledger/wasp/pull/2655) which might also help with this issue when I'm able to import the stronghold in wasp-cli but so far I was unable to to build the wasp-cli from his branch.
I'm getting these errors when trying to build wasp-cli from his branch:
```
cli\wallet\wallet.go:12:2: github.com/iotaledger/wasp-wallet-sdk@v0.0.0-20230702171756-c587ec0c31a2: replacement directory /home/luke/dev/wasp-wallet-sdk does not exist
cli\config\config.go:12:2: github.com/iotaledger/wasp-wallet-sdk@v0.0.0-20230702171756-c587ec0c31a2: replacement directory /home/luke/dev/wasp-wallet-sdk does not exist
```

**Comment by jorgemmsilva** [comment]
that PR depends on some changes to the wallet SDK afaik, that's why it hasn't been merged so far.

**Comment by lmoe** [comment]
It used to. The required wallet-sdk additions were moved to another repo - awaiting review. I wanted to wrap it all up on monday.

I wouldn't bother with the cli PR for now as it needs to be merged with current Wasp first.
