### ISSUE TITLE
Failur to run a wasp node locally : tools/local-set-up

### ISSUE THREAD

**Issue by imen2023-dot** [iotaledger/wasp-legacy#3142]
**Describe the bug**
I'm trying to setup a WASP Node in my local, to create a WASP Chain and a Smart Contract on,
I followed the following commands to run the WASP node on my local
**To Reproduce**

git clone https://github.com/iotaledger/wasp.git
cd wasp/tools/local-setup
docker-compose pull
docker volume create --name hornet-nest-db
docker volume create --name wasp-db
docker-compose up

**Screenshots**

i get this error : panic: invoke core component (INX) failed: could not build arguments for function "github.com/iotaledger/inx-app/inx".init.0.func1 (/go/pkg/mod/github.com/iotaledger/inx-app@v1.0.0-rc.1/inx/component.go:20): failed to build *nodebridge.NodeBridge: received non-nil error from function "github.com/iotaledger/inx-app/inx".provide.func1 (/go/pkg/mod/github.com/iotaledger/inx-app@v1.0.0-rc.1/inx/component.go:40): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9029: connect: connection refused"

.

**Comment by rpc5255** [comment]
I had this working yesterday 12/7/2023, but I am also getting the error stated above. Additionally, I'm receiving this message in the hornet-nest:

HORNET was not shut down properly, the database may be corrupted.
hornet-nest     | hornet-1:	Please restart HORNET with one of the following flags or enable "db.autoRevalidation" in the config.
hornet-nest     | hornet-1:	
hornet-nest     | hornet-1:	--revalidate:     starts the database revalidation (might take a long time)
hornet-nest     | hornet-1:	--deleteDatabase: deletes the database
hornet-nest     | hornet-1:	--deleteAll:      deletes the database and the snapshot files
hornet-nest     | hornet-1:	
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.(*Component).LogPanic
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/component.go:157
hornet-nest     | hornet-1:	github.com/iotaledger/hornet/v2/components/tangle.configure
hornet-nest     | hornet-1:		/scratch/components/tangle/component.go:197
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.(*App).configure.func1
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/app.go:460
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.forEachComponent
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/app.go:631
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.(*App).ForEachComponent
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/app.go:639
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.(*App).configure
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/app.go:458
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.(*App).initializeApp
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/app.go:541
hornet-nest     | hornet-1:	github.com/iotaledger/hive.go/app.(*App).Run
hornet-nest     | hornet-1:		/go/pkg/mod/github.com/iotaledger/hive.go/app@v0.0.0-20230629181801-64c530ff9d15/app.go:563
hornet-nest     | hornet-1:	main.main
hornet-nest     | hornet-1:		/scratch/main.go:8
hornet-nest     | hornet-1:	runtime.main
hornet-nest     | hornet-1:		/usr/local/go/src/runtime/proc.go:250
hornet-nest     | hornet-1:	2023-12-08T18:15:18Z	PANIC	App	application panic: 

![image](https://github.com/iotaledger/wasp/assets/41126486/411c8e30-d262-4cee-bb75-8a3aa5e333ed)
The wasp node is offline as well.

**Comment by rpc5255** [comment]
I ran ```docker volume rm wasp-db hornet-nest-db```  and this fixed my problem.

**Comment by imen2023-dot** [comment]
Firstly, thanks for responding. I've tried that, but I'm still encountering the same error. Could I have missed something while setting up my WASP node? On the dashboard, I'm seeing an error 404. and my hornet node still not running too.
![screenshot](https://github.com/iotaledger/wasp/assets/153308646/c50ac0ff-939a-4346-b182-e5777dd8fb05)
 i start over again and i I've tried executing 'docker compose build wasp' followed by 'docker compose up', i get this : 
![scren2](https://github.com/iotaledger/wasp/assets/153308646/95f1783e-c703-46e4-b484-ac8d225a855e)
 Unfortunately, nothing is appearing on the dashboard for either Hornet or the WASP dashboard.

**Comment by imen2023-dot** [comment]
when running docker logs wasp i get same error:   
PANIC   App     invoke component (NodeConn) failed: could not build arguments for function "github.com/iotaledger/wasp/components/nodeconn".init.0.func1 (/scratch/components/nodeconn/component.go:20): failed to build chain.NodeConnection: could not build arguments for function "github.com/iotaledger/wasp/components/nodeconn".provide.func2 (/scratch/components/nodeconn/component.go:66): failed to build *nodebridge.NodeBridge: received non-nil error from function "github.com/iotaledger/wasp/components/nodeconn".provide.func1 (/scratch/components/nodeconn/component.go:40): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:9029: connect: connection refused"

**Comment by yourina13** [comment]
i fixed when i return to an older version of wasp, i use wasp-1.0.1-rc.4 and with same steps it works .
