### ISSUE TITLE
Bug when using if with a condition based on some entropy value

### ISSUE THREAD

**Issue by nicob21** [iotaledger/wasp-legacy#3145]
**Describe the bug**
When using an `if` statement with a condition that was compute based on some random value.

**To Reproduce**
To reproduce you can use the following contract.
It will fail with the `if` statement and won't fail if you remove it.
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "@iota/iscmagic/ISC.sol";

contract Test {
    event Debug(bool val);

    function test() public returns (bool) {
        bytes32 e = ISC.sandbox.getEntropy();
        uint256 res = uint(e) % 3;
        bool won = res == 0;

        emit Debug(won);

        if (won) {
            return true;
        }
        
        return false;
    }
}
```

The following test file can be used to simulate a few transactions and display the value emitted by the `Debug` event.
We can see that the test crashed with the `if` statement and not without it.
```
import { ethers } from "hardhat";

describe("Test", function () {
  async function deployTest() {
    const Test = await ethers.getContractFactory("Test");
    const test = await Test.deploy();
    return { test };
  }

  describe("test", function () {
    it("play several times", async function () {
      const { test } = await deployTest();
      for (let i = 0; i < 10; i++) {
        const tx = await test.test()
        const receipt = await tx.wait()

        if (receipt) {
          const log: any = receipt.logs[0]
          const firstArg = log.args[0]
          console.log(Number(firstArg))
        }
      }
    })
  })
});
```

**Expected behavior**
We should be able to use an `if` statement with a value coming from entropy.

**Comment by dessaya** [comment]
@nicob21 I can't reproduce this. Can you provide more details? How exactly does the test crash?

Note that if you first estimate the gas and then use that exact value as the `gasLimit`, you may run out of gas because the random value changes between runs.

**Comment by nicob21** [comment]
Thanks for your reply.
On my side when I run the test above I get the following error.
But when I remove the if statement I don't get it anymore...
![Screenshot 2023-12-14 at 21 39 26](https://github.com/iotaledger/wasp/assets/18648191/9f661e24-85e4-48d3-a728-a7ea0dfb720b)

**Comment by dessaya** [comment]
Which network are you running against?

I don't know why the actual error message is not displayed, but again, I'm guessing the error is because behind the scene Hardhat is estimating gas and then using that value as gasLimit for the actual transaction. This is not correct when dealing with randomness. Please try specifying an arbitrary gasLimit (like 1000000).

**Comment by nicob21** [comment]
Got it, seems to work when specifying the gasLimit manually. 
Sorry about that and thanks a lot for your help :)
