### ISSUE TITLE
Add functionality to estimate allowance/storage deposit for native SC calls

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wasp-legacy#3265]
**Is your feature request related to a problem? Please describe.**

I couldn't come up with a better tittle, sorry 😅 . What I would like to have is a function to estimate the allowance/storage deposit I need to for example create a foundry in Solidity.

**Comment by jorgemmsilva** [comment]
you can use `/v1/chains/{chainID}/estimategas-offledger` or `/v1/chains/{chainID}/estimategas-onledger`
