### ISSUE TITLE
Check for IRC27 compatible Metadata in ERC721NFTs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wasp-legacy#3323]
**Is your feature request related to a problem? Please describe.**

Currently there is no check before trying to get certain metadata from an IRC27 NFT. So if you try to for example get the tokenURI from an ERC721NFT that on L1 doesn't have any metadata or any random metadata you get some none saying error.

**Describe the solution you'd like**

Would be nice if there is a check for IRC27 compatibility to return some sensible error messages

**Comment by jorgemmsilva** [comment]
we already provide some functionality for IRC27 metadata on TokenURI, more will be added in the context of this issue https://github.com/iotaledger/wasp/issues/3437
