### ISSUE TITLE
Unify type definitions

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wasp-legacy#3330]
**Is your feature request related to a problem? Please describe.**

Currently we have may user defined types for `NFTID`, `ISCChainID` and so on. But for some types like `ISCAgentID` we use structs with a single property

**Describe the solution you'd like**

I think for the best DX it would be nice to use the same approach everywhere if possible.

**Describe alternatives you've considered**

Keep as is. Currently to get the bytes from an NFTID `id`, I have to use `NFTID.unwrap(id)` which is not worse then getting the bytes from an ISCAgentID `id` which would be `id.data`. It is just inconsistent.

**Comment by jorgemmsilva** [comment]
some objects are represented as:
```
struct X {
    bytes data;
}
```
due to being larger than bytes32. 
As far as I understand trying to declare them as `type X is bytes` would result in some issues.

We cannot change this now as it would be breaking to any application using these types
