### ISSUE TITLE
Method handler crashes after using wasp node for some hours

### ISSUE THREAD

**Issue by arne-fuchs** [iotaledger/wasp-legacy#3354]
The method handler crashes after some hours of using the wasp node to talk to smart contracts.
Wasp nodes cannot accept any RPC calls after that and is therefore not reachable anymore.
This is the error (logs are attached):
`RPC method eth_getTransactionByHash crashed: cannot decode nil uint32 - method handler crashed`
**To Reproduce**
We can only investigate bug reports that can easily be reproduced and all information needed to reproduce this issue has been supplied with this issue. Please provide the steps to reproduce this issue in the easiest way possible:

1. Setup own private chain on a wasp node with 1 validator
1. Deploy a contract where you save a struct in a mapping
2. Call the function which puts the struct into the mapping repeatedly (and simultaneously). 
3. Wait a few hours
4. ???
5. Method hanlder crashes because of "cannot decode nil uint32"

**Network and versioning**
 - Type of L1 network: Shimmer Testnet
 - Type of Wasp chain: Private chain
 - Interaction method: ethers-rs function_call.legacy().send()
 - Interaction software: ethers-rs
 - Version of Wasp 1.0.2-rc1

[_testnet-wasp_logs(7).txt](https://github.com/iotaledger/wasp/files/14757306/_testnet-wasp_logs.7.txt)

**Comment by jorgemmsilva** [comment]
please update to [v1.0.3](https://github.com/iotaledger/wasp/releases/tag/v1.0.3)
does the issue persist?

**Comment by arne-fuchs** [comment]
After updating to 1.0.3 the RPC API is giving me following message: `could not get latest AliasOutput: have no active nor confirmed state`
In the logs I get 
`2024-03-26T11:50:46.793056706Z 192.168.0.1 POST /v1/chains/rms1pqkaw9lwue8qx8pl8j3c24gsm8340t9wf69y7cmuu2sh5ax08kjrslq6w2e/evm 200 error=""

2024-03-26T11:50:46.804121171Z 192.168.0.1 POST /v1/chains/rms1pqkaw9lwue8qx8pl8j3c24gsm8340t9wf69y7cmuu2sh5ax08kjrslq6w2e/evm 200 error=""

2024-03-26T11:50:46Z	WARN	go-ethereum	Served eth_estimateGas

2024-03-26T11:50:46.815142443Z 192.168.0.1 POST /v1/chains/rms1pqkaw9lwue8qx8pl8j3c24gsm8340t9wf69y7cmuu2sh5ax08kjrslq6w2e/evm 200 error=""

2024-03-26T11:50:47.070345386Z 127.0.0.1 GET /health 500 error=""`

@jorgemmsilva 
Do I need to do a clean install after updating?

**Comment by jorgemmsilva** [comment]
>could not get latest AliasOutput: have no active nor confirmed state

this is similar to the reason why you're getting "cannot decode nil uint32"

please share the wasp logs since the restart (including the settings log at the start).

btw, I assume you're using `node-docker-setup` right? you need to restart the entire system, not just the wasp container

**Comment by arne-fuchs** [comment]
[_testnet-wasp_logs(8).txt](https://github.com/iotaledger/wasp/files/14757979/_testnet-wasp_logs.8.txt)
Here are the logs since start.

I will restart the whole system :+1:

**Comment by arne-fuchs** [comment]
I've restarted the whole system and the error above still persists.
I once had the error before and it magically fixed by itself.

**Comment by jorgemmsilva** [comment]
I can't find the error you mentioned above in the logs you submitted above.

please set `--logger.level=debug` so we can get more information about what is happening.

**Comment by arne-fuchs** [comment]
The error `could not get latest AliasOutput: have no active nor confirmed state` is the answer from the api. I got it from ether-rs.
Here are the logs with debug log level.
[_testnet-wasp_logs(12).txt](https://github.com/iotaledger/wasp/files/14758185/_testnet-wasp_logs.12.txt)

**Comment by jorgemmsilva** [comment]
I see your node has pruning enabled (it is only keeping the last 10k states):
```
"pruningminstatestokeep": 10000,
```

I have the feeling the `cannot decode nil uint32` error happens when you try to query older blocks that your node doesn't have anymore.

regarding `could not get latest AliasOutput: have no active nor confirmed state`, that should fix itself after a while, once your node is able to sync itself with L1

**Comment by arne-fuchs** [comment]
That's weird, because typically a restart of the node fixes the problem right away. If it is a pruning problem, the error should persists after a restart. 
Ps: Node is synced and I can start posting transactions again. I'll let you know if it crashes again.

**Comment by jorgemmsilva** [comment]
Please re-read my last comment.

Closing the issue for now

**Comment by arne-fuchs** [comment]
Why do you let the method handler crash and not throw an error if trying to talk to that chain?

**Comment by jorgemmsilva** [comment]
"method handler crash" **is** an error
