### ISSUE TITLE
It is not possible to create a wasp node committee with more than one node.

### ISSUE THREAD

**Issue by IOTAC3PO** [iotaledger/wasp-legacy#338]
Following the steps in the documentation:
https://github.com/iotaledger/wasp/blob/master/documentation/docs/misc/runwasp.md
https://wiki.iota.org/wasp/misc/runwasp/

4 wasp nodes and 1 goShimmer node are created. All nodes running in a localhost environment. 
The 4 wasp nodes successfully connect to goShimmer on port 5000.
The 4 wasp nodes are accessible by http to port 7000/7001 etc showing the properties of the configuration file, config.json.
There is an initialized and funded wallet on each wasp node.

When creating a chain with : ./wasp-cli chain deploy --committee=0,1,2,3 --quorum=3 --chain=mychain --description="My chain"
it returns this error:

2021-08-18T07:59:50+02:00 WARN Peering udp/udpNetImpl.go:347 Dropping handshakeMsg from 127.0.0.1:4000 with pubKey=5gJMq6xhACwMNhmpLjPsNk2zdkc8GZ9x2FKBpN8TEyzC, error=key not found.

This error is displayed on all committee nodes.

But if it is possible to create a chain with a single node and the result is:

./wasp-cli chain deploy --committee=0 --quorum=1 --chain=C3POChain --description="My C3PO chain"
creating new chain. Owner address: 1FiCvsDvyRuh71dgUteG34QRGqCdna2QtKjoy7DVaSELG. State controller: LwxSGyTgo9Z5HxXWSr6YjZ2qww8KGi1EzU4yV5Yvt3tZ, N = 1, T = 1
creating chain origin and init transaction 8TwruvDasfkrky4FYAYcYApnL2Hq5fEgX1HCPXfbbcag.. OK
sending committee record to nodes.. OK
activating chain sfutpoJqUEuoEAxz6WUbqCiXY9cw9Sd4j6NeGFWXiEGb.. OK.
chain has been created successfully on the Tangle. ChainID: $/sfutpoJqUEuoEAxz6WUbqCiXY9cw9Sd4j6NeGFWXiEGb, State address: LwxSGyTgo9Z5HxXWSr6YjZ2qww8KGi1EzU4yV5Yvt3tZ, N = 1, T = 1

This error may be related to #212

**Comment by jorgemmsilva** [comment]
Adding trusted nodes manually should fix this issue: `wasp-cli peering trust <pubKey> <netID>`

But it feels that it should be something automatic, done by the `chain deploy` command.
What are your thoughts on the above @kape1395 @dessaya ?

**Comment by kape1395** [comment]
The trusted peering is considered a precondition for the `chain deploy`.
To keep the network safe, a node owner should manually decide, which nodes are trusted.

The `wasp-cluster` tool (only for testing) makes all the nodes to trust each other on startup.

A single node committee was successfully created, because a node trusts itself by default.

**Comment by kape1395** [comment]
I will add a command to get the current node's public key and update the docs to reflect the step of making the nodes to trust each other.

**Comment by kape1395** [comment]
I hope the updated docs resolve this issue.
Docs and the relevant `wasp-cli` commands are now in the develop branch.
