### ISSUE TITLE
Missleading error on wrong gaslimit

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#343]
Steps:

1. Running wasp-cluster with option `inMemory : true` on all nodes
2. Sending as tx with ether.js with following options:
```
    const provider = new ethers.providers.JsonRpcProvider(url);
    const signer = new Wallet(SIGNING_KEY, provider);

    const gas_limit = 10000;
    const tx = {
        from,
        to,
        value: ethers.utils.parseEther(amount_in_eth),
        nonce: provider.getTransactionCount(from, "latest"),
        gasLimit: ethers.utils.hexlify(gas_limit), 
        gasPrice: provider.getGasPrice(),  
      }

    const tx1 = await signer.sendTransaction(tx);
    const receipt = await tx1.wait();
```
3. Running the command gives the following error ```UnhandledPromiseRejectionWarning: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"method handler crashed\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x388d7dbe3a0aad0bec95e1aa60838f458a9dc392af527da4831171ade8fcc6d5\"],\"id\":55,\"jsonrpc\":\"2.0\"}", requestMethod="POST", 
url="<MY WONDERFUL WASP URL>", code=SERVER_ERROR, version=web/5.4.0) ```
4. In the logs it gives me an error regarding wrong gaslimit ```DEBUG   Chains.izcbUY..c        runvm/runtask.go:79     runTask, ERROR running request: M7exjP9mH7f6FavXjEe1eX7pNPBsVKjPx4TpPXTfo4C199, error: panic in VM: assertion failed: assertion failed:  intrinsic gas too low: have 10000, want 21000```

**Comment by dessaya** [comment]
This should be fixed in develop branch. Please reopen if that's not the case. Thanks!
