### ISSUE TITLE
`debug_traceTransaction` returns empty gasUsed

### ISSUE THREAD

**Issue by vbaranov** [iotaledger/wasp-legacy#3433]
`debug_traceTransaction` returns empty gasUsed where it should be non-empty.

**To Reproduce**
Request trace for transaction `0xec59dd233c14ea465b0d6bd4a30ef9ab59919a850eb0d8d49b6388341d073a28`. gasUsed returns "":
```
curl -s \
  -H "Content-Type:application/json;charset=utf-8" \
  -d "{
      \"jsonrpc\": \"2.0\",
      \"id\": 1,
      \"method\": \"debug_traceTransaction\",
      \"params\": [
          \"0xec59dd233c14ea465b0d6bd4a30ef9ab59919a850eb0d8d49b6388341d073a28\",
          { \"tracer\": \"callTracer\"}
      ]
  }" \
https://#{shimmer_testnet_endpoint} | jq ".result.gasUsed"
""
```

**Expected behavior**
`gasUsed` should return non-empty value.

**Network and versioning**
 - Type of L1 network: Shimmer Testnet
 - Type of Wasp chain: ShimmerEVM Testnet
 - Interaction method: JSON/RPC HTTP
 - Interaction software: API
 - Version of Wasp I don't know

**Comment by jorgemmsilva** [comment]
fixed on the testnet 👍
