### ISSUE TITLE
Wasp evm/rpc accepts duplicate transaction nonce

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#346]
Current branch/commit: develop@92af65f7677d4fbb15763c62edf1d08be35d37a7

Steps To reproduce:
1. started wasp cluster with `inMemory: true` configuration
2. get the latest nonce with `await provider.getTransactionCount(from, "latest");` e.g. `2`
3. send transaction (e.g. ether.js)
```javascript
    const provider = new ethers.providers.JsonRpcProvider();
    const signer = new Wallet(SIGNING_KEY, provider);

    const gas_limit = 30000;
    const nonce = 2
    console.log(`Nonce: ${nonce}`);
    const tx = {
        from,
        to,
        value: ethers.utils.parseEther(amount_in_eth),
        nonce,
        gasLimit: ethers.utils.hexlify(gas_limit), // 100000   
        gasPrice: provider.getGasPrice(),  
      }

    const tx1 = await signer.sendTransaction(tx);
    const receipt = await tx1.wait(); 
```

4. You can send the transaction over and over again.

I tried to reproduce this with ganache and it will result in:
`Error: processing response error (body="{\"id\":52,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"the tx doesn't have the correct nonce. account has nonce of...`

**Comment by dessaya** [comment]
This should be fixed in develop branch. Please reopen if that's not the case. Thanks!
