### ISSUE TITLE
Method handler crashes on eth_getTransactionReceipt call with unkown hash

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#348]
Current branch/commit: develop@92af65f7677d4fbb15763c62edf1d08be35d37a7

Steps
1) Start disposable cluster `wasp-cluster start -d`
2) Create chain/committee, deploy evm chain and start rpc gateway
3) Send `eth_getTransactionReceipt` with unkown hash:
```javascript
    const fs = require('fs');
    const SIGNING_KEY = fs.readFileSync(".secret2").toString().trim();

    const provider = new ethers.providers.JsonRpcProvider(MY_WASP_RPC);
    const signer = new Wallet(SIGNING_KEY, provider);

    const txHash = '0xd810471d1710df724314757afeb9533786d55bfe5e9df1a8584c154e5e91187f';

    console.log(await provider.getTransactionReceipt(txHash)); //should output null
```

This will throw an error:
`
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"method handler crashed\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0xd810471d1710df724314757afeb9533786d55bfe5e9df1a8584c154e5e91187f\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="SOME_URL", code=SERVER_ERROR, version=web/5.4.0
`

Expected Behavior:
According to the alchemy docs (https://docs.alchemy.com/alchemy/documentation/apis/ethereum#eth_gettransactionreceipt) the `eth_transactionReceipt` call shoud return `null` on unkown tx hashes.

I tested this also on a local ganache environment and the same code will return `null`

**Comment by dessaya** [comment]
Should be fixed in develop. Please reopen if that's not the case.
