### ISSUE TITLE
cannot find -lwasmtime

### ISSUE THREAD

**Issue by iamadamsiwy** [iotaledger/wasp-legacy#39]
_ubuntu@ubuntu:~/wasp$ go run main.go
 github.com/bytecodealliance/wasmtime-go
**/usr/bin/ld: cannot find -lwasmtime**
collect2: error: ld returned 1 exit status_

the wasmtimevm could not be retrieved on wasmtime branch
Ubuntu 20.04.1 LTS

**Comment by iamadamsiwy** [comment]
By October 2020 it seams there are no pre-build binaries for rpi arm64 architecture

`Error: Sorry! Wasmtime currently only provides pre-built binaries for x86_64 architectures.`

Source: https://kevingzhang.github.io/posts/run-wasm-in-raspberry-pi-4-today/

**Comment by lunfardo314** [comment]
not relevant anymore
