### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by anistark** [iotaledger/wasp-legacy#390]
wasp uses [wasmtime go library](https://github.com/bytecodealliance/wasmtime-go) which doesn't work on M1 right now.

Running `go install` shows:
```
# github.com/bytecodealliance/wasmtime-go
ld: library not found for -lwasmtime
```

Once wasmtime-go [supports M1](https://github.com/bytecodealliance/wasmtime-go/issues/53), which in turn is stuck on [Github CI support](https://github.com/actions/virtual-environments/issues/2187), wasp should work as well.

Alternatively, if anyone has any idea around making it work without github ci support, would be great.

**Comment by howjmay** [comment]
I have opened a small PR(https://github.com/iotaledger/wasp/pull/774) to support compiling on M1 machines. This may temporarily solve the problem

**Comment by tuddman** [comment]
Requirements:
- Go `1.17`
- Rust `stable-aarch64-apple-darwin `  known to work on `1.58.1`

```
## build wasmtime
git clone https://github.com/bytecodealliance/wasmtime.git
cd wasmtime
git submodule update --init
cargo build -p wasmtime-c-api --release

cd ..

## build wasmtime-go
git clone https://github.com/bytecodealliance/wasmtime-go
cd wasmtime-go
./ci/local.sh ../wasmtime

cd path-to-wasp
go mod edit -replace=github.com/bytecodealliance/wasmtime-go=<wasmtime-go path>
make install
```
