### ISSUE TITLE
EVM: RPC endpoint issues

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#392]
Encountered the following 2 EVM rpc implementation issues while writing a smart contract:

- [ ] I had to explicitly set the gas limit (0 works) in my deploy tools to interact, since it was unable to request the gas from the node apparently; Maybe that function is not implemented?
- [ ] I wrote a simple faucet smart contract and tried to deploy it - the deployment worked but while interacting with it I got a error while trying to call any function on it. It looks like it might be breaking in a hexify function or smth on the node side. I deployed it to the BSC testnet after that and there it worked as expected. I suspect the node is used for some argument conversion and is returning something that might not be what it is expecting:

Error:
```
(node:1406915) UnhandledPromiseRejectionWarning: Error: invalid hex string (argument="value", value="-0x0eef28", code=INVALID_ARGUMENT, version=bytes/5.4.0)
    at Logger.makeError (/home/dave/ethereum/faucet/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/dave/ethereum/faucet/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
```
Deployed smart contract:

```solidity
pragma solidity ^0.8.3;

/**
 * @title   Simple Faucet
 * @author  Dave de Fijter // IOTA Foundation
 */


contract SimpleFaucet {

    mapping (address => bool) private requestedAddresses;

    constructor() payable {
    }   

    receive() external payable {
    }   

    fallback() external payable {
    }   

    function getBalance() public view returns (uint) {
        // See how many native tokens are in the contract
        return address(this).balance;
    }   

    function requestFunds(address payable _to) public payable {
        // Request some funds to a provided address
        // Each address can only receive faucet tokens once
        require(10 ether >= address(this).balance, "Not enough funds in the faucet to send!");
        require(!requestedAddresses[_to], "This address already received some faucet tokens...");
        (bool sent, ) = _to.call{value: 10 ether}("");
        require(sent, "Failed to send tokens");
        requestedAddresses[_to] = true;
    }

}
```

Reproducable by deploying this contract and trying to call any function it, for example `getBalance`

**Comment by dessaya** [comment]
This was caused by having `gas: 0` in `hardhat.config.ts`. Removing that apparently solves both issues.
