### ISSUE TITLE
Websockets seem to halt the execution of smart contracts

### ISSUE THREAD

**Issue by lmoe** [iotaledger/wasp-legacy#398]
Unfortunately I can't offer an extensive log, but just speak out of the experience I made throughout the testing.

The execution of the current fairroulette contract emits a few events which are sent via Nanomsg. Our current Websocket implementation listens to these events and publishes them through a Websocket port.

Somewhere in these stages, (this could also mean that the Nanomsg itself is the reason), Wasp behaves very uncoorperative. For example: Messages being dropped, whole execution halts at any random moment, the WS connection suddenly dies. Sometimes this is unrecoverable and requires the deletion of the Waspdb. Once I got this error message after restarting wasp `storeSyncingData not needed: stateOutput is nil`

I have experienced that, as soon as I drop off the Websocket connection and restart Wasp, the execution works reliable again.

**Comment by dessaya** [comment]
Fixed in #399
