### ISSUE TITLE
Malformed module

### ISSUE THREAD

**Issue by adastraproterra** [iotaledger/wasp-legacy#562]
root@v278:/home/pea# cd /home/pea/wasp
root@v278:/home/pea/wasp# go build -tags rocksdb
build github.com/iotaledger/wasp: cannot load embed: malformed module path "embed": missing dot in first path element

**Comment by jorgemmsilva** [comment]
you're using a wrong command to build the project, the error tells you what is wrong, it lacks a path, it should be something like: `go build -tags rocksdb .`

anyway, we recommend building the project using `make build`

**Comment by adastraproterra** [comment]
I did it like you said. But same error.

**Comment by adastraproterra** [comment]
I did 
$ git clone https://github.com/iotaledger/wasp.git
$ cd wasp
$ make install

Then that error occured.

**Comment by jorgemmsilva** [comment]
@roughneckgermany what `go` version are you using?

**Comment by adastraproterra** [comment]
1.13.8

**Comment by jorgemmsilva** [comment]
okay, please try to update to the latest (`1.17.3`)

**Comment by adastraproterra** [comment]
> okay, please try to update to the latest (`1.17.3`) 

Worked
