### ISSUE TITLE
Add Pull request template 

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wasp-legacy#582]
Hi 👋🏻 

Short question:
Should PRs be made to the develop branch or to the main branch? I guess to develop?

And should the wiki pull the documentation from the develop or main branch?

If you tell me how you want it I can create a PR template for this repo or you can do it yourself of course :)

**Comment by jorgemmsilva** [comment]
that is definitely a great idea, please feel free to create a template :slightly_smiling_face: !

my only suggestion is that the PR should target `develop` and ask users to read the [contributing docs](https://github.com/iotaledger/wasp/blob/master/documentation/docs/contribute.md).

Thanks!
