### ISSUE TITLE
wasp node failure with chain deploy: returns 404

### ISSUE THREAD

**Issue by DocBO** [iotaledger/wasp-legacy#584]
Hello,
My wasp node is running in a docker and connects to a goshimmer in the same docker bridge network. (goshimmer node seems to be fully ok and running, except: found no faucet state of at least 1000....00000 Tokens)

Wasp node has no startup problems and api-connection is ok (---> Total 0 chain(s) in wasp node http://127.0.0.1:9090).

But if I try to deploy a chain with
```
./wasp-cli chain deploy --committee=0 --quorum=1 --chain=mychain --description="My chain"
```

the wasp logs this:
```
wasp     | 2021-11-07T08:57:52Z	INFO	webapi/adm	admapi/committeerecord.go:69	Committee record saved. Address: Committee(Address: aeA...eVC Nodes:[127.0.0.1:4000])
wasp     | 2021-11-07T08:57:52.629833827Z 172.18.0.1 POST /adm/committeerecord 201 error=""
```

which seems also ok, but the wasp-cli returns this:

```
creating new chain. Owner address: 1FnS...jXVe. State controller: ZP...jVR, N = 1, T = 1
creating chain origin and init transaction.. FAILED: CreateChainOrigin: unable to read error from response body: invalid character 'i' looking for beginning of value repsonseBody: internal server error, error: code=404, message=Not Found
error: DeployChain: CreateChainOrigin: unable to read error from response body: invalid character 'i' looking for beginning of value repsonseBody: internal server error, error: code=404, message=Not Found
```

Seems to be a 404 response but why and on which server? Strangely enough the local wallet Balance decreased (without creating a chain):
Address index 0
  Address: 1Fn...5jXVe
  Balance:
    IOTA: 999000 (goes down every time I tried)
    ------
    Total: 999000

my config.json (I think standard more or less)
```
{
  "database": {
    "directory": "waspdb"
  },
  "logger": {
    "level": "debug",
    "disableCaller": false,
    "disableStacktrace": true,
    "encoding": "console",
    "outputPaths": [
      "stdout",
      "wasp.log"
    ],
    "disableEvents": true
  },
  "network": {
    "bindAddress": "0.0.0.0",
    "externalAddress": "auto"
  },
  "node": {
    "disablePlugins": [],
    "enablePlugins": []
  },
  "webapi": {
    "bindAddress": "0.0.0.0:9090",
    "adminWhitelist": ["127.0.0.1", "172.18.0.1"]
  },
  "dashboard": {
    "auth": {
      "scheme": "basic",
      "username": "...",
      "password": "..."
    },
    "bindAddress": "0.0.0.0:7000"
  },
  "peering":{
    "port": 4000,
    "netid": "127.0.0.1:4000"
  },
  "nodeconn": {
    "address": "goshimmer:5000"
  },
  "nanomsg":{
    "port": 5550
  }
}
```

**Comment by DocBO** [comment]
I think I have traced down the error to the goshimmer node, which shows exactly at the same time the following warning:

```
goshimmer    | 2021-11-08T20:02:16Z	WARN	WebAPI	webapi/plugin.go:72	Request failed: code=404, message=Not Found
```

**Comment by dahof1** [comment]
I have the same error, i guess it is since goshimmer 0.8

**Comment by jorgemmsilva** [comment]
Thanks for reporting this @dahof1 !

We recommend using a specific version of Goshimmer, as it is software with an active on-going development and is prone to fresh bugs / breaking changes.

https://wiki.iota.org/wasp/welcome#prerequisites

I've noticed that this version recommendation is missing on the proper "how to run a node" page.
https://wiki.iota.org/wasp/guide/chains_and_nodes/running-a-node

@lucas-tortora would you mind adding that note please? :pray:

**Comment by dahof1** [comment]
Hi @jorgemmsilva ,

there might be a problem when using the latest working goshimmer docker image (v0.7.7). As far as i can see the goshimmer team didn't published a docker image for v0.7.7 on dockerhub.

**Comment by jorgemmsilva** [comment]
yes, you would need to build goshimmer yourself.

alternatively its possible to use the goshimmer node we provide for the testnet :slightly_smiling_face: 

https://wiki.iota.org/wasp/guide/chains_and_nodes/testnet#endpoints

**Comment by DocBO** [comment]
Thanks for the clarifications

**Comment by lucas-tortora** [comment]
> Thanks for reporting this @dahof1 !
> 
> We recommend using a specific version of Goshimmer, as it is software with an active on-going development and is prone to fresh bugs / breaking changes.
> 
> https://wiki.iota.org/wasp/welcome#prerequisites
> 
> I've noticed that this version recommendation is missing on the proper "how to run a node" page. https://wiki.iota.org/wasp/guide/chains_and_nodes/running-a-node
> 
> @lucas-tortora would you mind adding that note please? pray

Sure, :) .  https://github.com/iotaledger/wasp/pull/589

**Comment by bpieres** [comment]
> I think I have traced down the error to the goshimmer node, which shows exactly at the same time the following warning:
> 
> ```
> goshimmer    | 2021-11-08T20:02:16Z	WARN	WebAPI	webapi/plugin.go:72	Request failed: code=404, message=Not Found
> ```
Hi How do you solved??
