### ISSUE TITLE
Call eth_getBlockByHash returns always null (evmlight)

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#600]
Version: develop
EVM Flavor: evmlight

RPC call `eth_getBlockByHash` returns null for every block hash.

Example (by getting block by number first)
```bash
curl <RPC-URL> -X POST     -H "Content-Type: application/json"     -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params": ["latest",false],"id":1}'

# { ..."hash":"0x6a09626d31efb91d315723aa8bd81f50f0cf929393b76e25b5a2b835e601e58a", ...}

curl <RPC-URL> -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x6a09626d31efb91d315723aa8bd81f50f0cf929393b76e25b5a2b835e601e58a", true],"id":60}'

# {"jsonrpc":"2.0","id":60,"result":null}
```

The same calls work on testnet (which standard evm flavor)

**Comment by dessaya** [comment]
I found that this happens with blocks with 0 transactions (e.g. when enabling the new block time feature and not sending any transactions). There is a fix for this specific case in #601.
