### ISSUE TITLE
Chain (evm/evmlight) returns timeout for every write call

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#602]
Branch: Develop
EVM Flavor: evmlight

Running a evm chain for several days the chain returned suddenly a timeout for every write call (via rpc). The chain was setuped with a block time which also paused and no block gets "minted" since the timeout error. 

Example log from the RPC Interface for the timout response:

```bash
Nov 13 14:46:53 wasp-1-sazsjtfk wasprpc[410928]: REQUEST:  {"method":"eth_sendRawTransaction","params":["0xf8851380826906949a03bd40f5719353741f6e996dc12f93e4f88b7a80a4f3b837910000000000000000000000000000000000000000000000000000000000e4e1c0820456a070f5672731bd7a572a33a3b0ff35bab80cf33412998d8d7516aef33a3f14f6efa04058ee8a5a74bbe52f157378afc036b4bbd5531743f61226574787cb6744c3ae"],"id":49,"jsonrpc":"2.0"}
Nov 13 14:46:53 wasp-1-sazsjtfk wasprpc[410928]: RESPONSE: {"jsonrpc":"2.0","id":49,"error":{"code":-32000,"message":"GET http://10.1.0.183:9090/chain/tBDmLX2kBEXRCuE1yKrFsTYTwmB3ey5qQzPXMpQ4AVsV/request/2qej9Z3uDfjAraRPAvR5J7Ncn1TkgEtieWUK323LMy5g9EP/wait: 408: Timeout while waiting for request to be processed"}}
```

I checked the wasp logs but i cannout find any special error output. I also attached the logs.  
[wasp-logs.zip](https://github.com/iotaledger/wasp/files/7532287/wasp-logs.zip)

All nodes have enough space left. Account which is running the RPC Interface has balance (IOTA: 2510)

**Comment by dahof1** [comment]
Update: 
Somehow it feels like it has something do to with the transaction nonce. The waspdb was not purged between the various develop releases and write calls stopped working after some block time. The strange thing is that i also don't get nonce errors anymore when i send some wrong nonce. I only see the the timout errors.

Just speculation but could it be that the nonce get out of sync with the new block time feature?

**Comment by dessaya** [comment]
I can't find anything interesting in the logs either.

Why do you think that the nonce is involved? (I take it you are referring to the nonce in the ethereum transaction).

Does the timeout only happen with the jsonrpc calls? Does something like `wasp-cli chain info` or `wasp-cli chain deposit` still work?

**Comment by dahof1** [comment]
Hi @dessaya,

it was just a wild thought :) because i spotted some (ethereum transaction) nonce errors before the timout occours. But it was just speculation.

`wasp-cli chain info` works, `wasp-cli chain deposit` returns a timout.

**Comment by dessaya** [comment]
Ok, so then I guess the consensus is somehow stuck.

@lunfardo314 @kape1395 maybe you can provide some insight?

**Comment by dahof1** [comment]
Today in the morning i setuped a fresh chain, wiped all db, logs etc. Returned in the afternoon to my setup and experienced again the timout error (on deposit, rpc was not running). I dont know if you guys can reproduce this... i will try it again (wipe all again, init a new seed...).

**Comment by Juliusan** [comment]
As I see it, level 1 took too long to approve the transaction. Am I right that you set the request handling timeout to 1 minute? I see, that request was received by node 0 at 2021-11-13T14:45:53Z and it was passed to L1 at 2021-11-13T14:45:59Z. However updated state has been received from L1 only at 2021-11-13T14:47:03Z. So the timeout occurred ~10 seconds before the success. But the request was accepted correctly.

**Comment by Juliusan** [comment]
By the way, I assume, the logs were produced using commit `a6aed6275b157d92b76c01ebcbef19fdb9f2a382`. It is important to know the exact version, as `develop` branch changes a lot and it might get confusing reading logs of different wasp version than the code is at.

**Comment by dahof1** [comment]
Hi @Juliusan,
the logs where produced with commit 3cd1e064aaeaee47ccc064b4df7ad848fb128f4e

**Comment by dessaya** [comment]
Thanks @Juliusan !!

@dahof1 So if the request is being accepted, then after something like `wasp-cli chain deposit IOTA:100` you should be able to check the balance with `wasp-cli chain balance <your agent id>` and see that it actually changed after a while, even if you got the timeout error. Is this the case?

**Comment by Juliusan** [comment]
@dahof1, thanks, I checked. It is one pull request earlier than I guessed. My comments should still stand.

**Comment by dahof1** [comment]
Hi @dessaya,

mmh... no unfortunately not. The balance stays the same. How long could it take? I waited a couple of minutes.

**Comment by dahof1** [comment]
I could reproduce this issue with an other chain:

EVM Flavor: evmlight
Commit: ebf4133b8cda2fb2cb74fefbc1e5caad32e7d05c

Created the chain on 2021-11-18, around 8:30 pm. Chain was running smoothy until block #13013 (blockTime 3s). Since then no block gets minted anymore.

`wasp-cli chain deposit IOTA:1` gives timout,  `wasp-cli chain balance A/1GYusVqm3ip8Guq5dFFqYV5XLXsug1MPqNe5kC2Kcx1PZ::00000000` stays the same.

**Comment by fijter** [comment]
Hey guys, thanks for reporting. The bug is likely an issue due to a bug in GoShimmer - Given our full focus is on converting to Hornet for mainnet support right now we prefer not to spend much time on debugging this until we can try and replicate it on Hornet. Let's park it for now and revisit once we have a first version of that and go from there. If it's still an issue at that point we surely need to get to the bottom of it. Hope you understand.

**Comment by dahof1** [comment]
Thanks @fijter for the update! Then let's do it like this

**Comment by AdamEunson** [comment]
@fijter just wondering if there has been any movement on this or any temporary fix. We're looking at the Tangle Labs NFT launch on Friday, and this is currently a blocker to the release for us, so would be interesting to see what we can do to ensure a smooth NFT release. Thanks

**Comment by jigsnptel** [comment]
As I see it, level 1 took too long to approve the transaction. Am I right that you set the request handling timeout to 1 minute? I see, that request was received by node 0 at 2021-11-13T14:45:53Z and it was passed to L1 at 2021-11-13T14:45:59Z. However updated state has been received from L1 only at 2021-11-13T14:47:03Z. So the timeout occurred ~10 seconds before the success. But the request was accepted correctly.

how can i see all these details, once i have deployed contract using remix and metamask

**Comment by jigsnptel** [comment]
pls help

**Comment by jorgemmsilva** [comment]
The current EVM implementation on `master` branch will be deprecated soon. 
We will be releasing the new shimmer-compatible ISC which will run in the new network (currently the `devleop` branch). A lot of things have changed and its likely this issue no longer applies.
