### ISSUE TITLE
Wiki Faucet plugin - no seed

### ISSUE THREAD

**Issue by MR1991** [iotaledger/wasp-legacy#603]
https://wiki.iota.org/wasp/guide/chains_and_nodes/running-a-node#enable-txstream-and-faucet-plugins

Enabling faucet plugin gives me the following error upon running my goshimmer node

Faucet  node/plugin.go:86       a seed must be defined when enabling the faucet plugin

Instructions to be added to the page.

**Comment by jorgemmsilva** [comment]
Please create goshimmer-related issues on the goshimemer repo: https://github.com/iotaledger/goshimmer

Feel free to use the testnet goshimmer in order to experiment with smart contracts without having to setup your own goshimmer node: https://wiki.iota.org/wasp/guide/chains_and_nodes/testnet
