### ISSUE TITLE
Unable to build schema tool

### ISSUE THREAD

**Issue by NomanNasirMinhas** [iotaledger/wasp-legacy#607]
I am trying to build schema tool in master branch by using go language commands but I am getting 
`build github.com/iotaledger/wasp/tools/schema: cannot load io/fs: malformed module path "io/fs": missing dot in first path element` error. I am using Ubuntu OS. Screen shot of the error and go language is version is attached as well. I have tried to build it from "tools" directory as well as from "wasp" directory. 
![Screenshot from 2021-11-16 14-26-30](https://user-images.githubusercontent.com/28532113/141958851-66953bc5-ac32-4031-906f-8d6cd1fc1e04.png)

**Comment by jorgemmsilva** [comment]
@NomanNasirMinhas what go version are you using?

**Comment by NomanNasirMinhas** [comment]
> @NomanNasirMinhas what go version are you using?

1.13.8 it's visible in the screenshot

**Comment by jorgemmsilva** [comment]
you should update to the latest version.

**Comment by NomanNasirMinhas** [comment]
> you should update to the latest version.

Thanks man. That solved the issue. Just for anyone else facing this issue, the command "sudo apt install golang-go" doesn't install the latest version of go language. I had to manually download it from go-language website and install.

**Comment by jorgemmsilva** [comment]
you might have to `sudo apt-get update` :slightly_smiling_face:
