### ISSUE TITLE
WASP communication with public IPs

### ISSUE THREAD

**Issue by gizmotangle** [iotaledger/wasp-legacy#622]
I try to setup a wasp communitee with different wasp members (not in the same local network)

In our working setup we have servers with internal/external IP adresses. When we have the communication between the nodes on an the internal network (10.x.x.x), there I can create the peering trust and new chains, all works fine. When I try to setup the trust on this nodes with there external IP adresses, I got a an error (500 error="cannot create peer network config provider") on chain deploy. The peering is listed as up but the chain ID is there with error message. code=404, message=Chain not found. Any sugestions whats wrong?

**Comment by jorgemmsilva** [comment]
Hello, sorry for the late reply.

Do you still have an issue? I don't think we have such an error `"cannot create peer network config provider"`. So its hard to what the cause may be.

The software has evolved a lot since november, its possible you won't face this issue on the newer versions.
