### ISSUE TITLE
Error in packages/vm/core/accounts/impl.go

### ISSUE THREAD

**Issue by brunoamancio** [iotaledger/wasp-legacy#82]
The following line is using the wrong parameter. It should use ParamAmount instead of ParamAgentID.
https://github.com/iotaledger/wasp/blob/411ccd156a2080838922e67272fa730a7c9de3ff/packages/vm/core/accounts/impl.go#L162

**Comment by lunfardo314** [comment]
good catch, thanks! That happens when the function is not covered with tests (yet). This branch is not even finished.

**Comment by lunfardo314** [comment]
Fixed in https://github.com/iotaledger/wasp/commit/1f44c21cb5b5021dc25e901f58aed51414c882b4
