### ISSUE TITLE
Happy to contribute

### ISSUE THREAD

**Issue by cadencedatasoft-dot-in** [iotaledger/wasp-legacy#857]
Hi There, I will be happy to contribute. Please advice

**Comment by jorgemmsilva** [comment]
Hello there, sorry for the late reply, glad to see you're interested in contributing.
There will be a new release soon, so a good way to help would be testing the new version and creating issues for anything that is relevant. 
Join the discussion on discord to be up-to-date with the latest developments.
Pull requests to improve the  documentation are always welcomed for example.

Please see the README: https://github.com/iotaledger/wasp#contributing

**Comment by cadencedatasoft-dot-in** [comment]
Hi Jorge,

Appreciate your response. I have already added myself to the discord channel.

Will start watching for updates. Feel free to pin me should you need help on something very specific.

On a separate node I will be keen to join IOTA team if there was any open position. - thank you.

Regards,
--Anand Bhalve
+91 9850 711 663
GMT +5:30
www.cadencedatasoft.in<http://www.cadencedatasoft.in>

________________________________
