### ISSUE TITLE
Docs - Stardust Updates

### ISSUE THREAD

**Issue by charlesthompson3** [iotaledger/wasp-legacy#897]
### Description
With the upcoming changes, some articles in the documentation may require updates and versioning.

### Motivation
We need to be able to launch products with their respective docs to improve the overall developer experience.

### Requirements
The following pages may require updating. Please feel free to add or remove any items you see fit.

- ISCP architecture
- On-ledger requests may need some tweaking
- Running a node
- Using Docker
- Configuring wasp-cli
- Setting up a chain
- testnet
- Wasm VM section
- Dev tools
- Example Projects

### Are you planning to do it yourself in a pull request?
To what extent I can, but the @iotaledger/tech-writers team will require support from the developers to know exactly what should be updated.

**Comment by lucas-tortora** [comment]
Parent issue: https://github.com/iotaledger/stardust-project/issues/45
